### ISSUE TITLE
Collection MVP UI Design

### ISSUE THREAD

**Issue by Heesoomoon** [wellcometrust/wellcomecollection.org#1064]
## Objectives
To define Image Search UI based on the MVP requirements and explore 'nice to haves' to validate with users

## UI Elements
Search Field, Search Results, Item Page
Mobile first

## Tasks
- [x] Sketch UI based on prioritised information
- [x] Review sketch with the team (kickoff?)
- [x] Sketch Search Results UI for mobile and desktop
- [x] Create wireframe with actual contents
- [x] Review with the team
- [x] Revise based on feedback
- [x] Create/update tickets with the wireframes and UI specification
- [x] Tomi to create visual design
