### ISSUE TITLE
WC Digital Style Guide Audit

### ISSUE THREAD

**Issue by Heesoomoon** [wellcometrust/wellcomecollection.org#1082]
## Objectives
To review the style guide and identify modules to be revised or created 

## Tasks
- [x] Review style guide and identify missing modules
- [ ] Meet with Jenn to collect feedback
- [ ] Work with Tomi to update style guide

**Comment by jamesgorrie** [comment]
Worth merging into #226

**Comment by jennpb** [comment]
Being dealt with as part of design system audit
