### ISSUE TITLE
Collection MVP+ UI Design

### ISSUE THREAD

**Issue by Heesoomoon** [wellcometrust/wellcomecollection.org#1098]
## Objectives
To explore the UI elements we want to validate with users and create UI patterns we may need in future Collection release

## UI Elements
**Collections Landing**
- Search with filters
- Collection categories
- Featured list of collection

**Search Results**
- All item types
- Image Thumbnail display rule (layout, detail/full, # of thumbnails per row, image size, etc.)
- Image Preview
- Pagination vs. Infinite Scrolling

**Item Page**
- All item types
- Image display in the item page (size, overlay, etc.)
- Information layout (one view vs. modal view)
- Copyright information
- Related series (e.g. pages, chapters, books)
- Related items 
- Related search

## Tasks
- [x] Sketch UI for mobile and desktop
- [x] Review sketch with the team
- [x] Create design with actual contents
- [ ] Review with the team
- [ ] Revise based on feedback
- [ ] Follow up with Hayley to validate the design
