### ISSUE TITLE
Create meta unit component

### ISSUE THREAD

**Issue by davidpmccormick** [wellcometrust/wellcomecollection.org#1139]
## Type
- ✨ Feature

## UI Requirements
![screen shot 2017-07-10 at 10 54 34](https://user-images.githubusercontent.com/1394592/28012784-cf935e32-655e-11e7-9308-569cbd08d5dd.png)

## Acceptance Criteria
- [x] it should have a Helvetica Neue medium heading
- [x] it should accommodate free text (Helvetica Neue light), a list of links, a date or a date range
- [x] it should be underlined with a grey key-line

The design is (virtually) identical to what we currently have built (but not implemented) as a 'tags' component. This should almost certainly replace that component.

## Problem to be solved / User Story
In order to
 _learn more about an item_

As a
 _user_

I need/want/expect 
_to be able to read clearly labeled blocks of meta information about the item_
