### ISSUE TITLE
PP: Roadshow

### ISSUE THREAD

**Issue by Heesoomoon** [wellcometrust/wellcomecollection.org#1207]
## Type
UX Discovery

## Objectives
To bring the team member to up to date

## Tasks
- [x] Meet with Nicole from Events team to collect feedback
- [x] Meet with Danny to collect feedback
- [x] Follow up with Emily
