### ISSUE TITLE
PP: UX Discovery User Research Plan

### ISSUE THREAD

**Issue by Heesoomoon** [wellcometrust/wellcomecollection.org#1213]
## Type
UX Discovery

## Objectives
To draw up a research objectives and plan

## Tasks
- [x] Brainstorm on what we want to investigate
- [x] Discuss the methods with James
- [x] Work with Tomi to prepare the comps

**Comment by Heesoomoon** [comment]
We will discuss the prototype plan during the team planning meeting on 26 July.
