### ISSUE TITLE
Public Program: User Research Prototype

### ISSUE THREAD

**Issue by Heesoomoon** [wellcometrust/wellcomecollection.org#1286]
## Objectives
To build a click through prototype using Invision with the latest design of What's On, Exhibitions and Events (See #1272 for user research objectives)

## Tasks
- [x] Update the design per feedback
- [x] Create the prototype
- [x] Share a link with the team and collect feedback

**Comment by Heesoomoon** [comment]
**Prototype Links**
Concept 1 https://invis.io/VMCVK7QR8
Concept 2 https://invis.io/3HCTLE9TR

Please note, only few links are active.
- Navigation: anchor links and tags
- Exhibition: Museum of Modern Nature
- Events: Nature Wanders (This links to the event template on Cardigan)

**Comment by jennpb** [comment]
I'm happy with the prototypes with a few spelling corrections (accessibility and programme). Thanks!
