### ISSUE TITLE
AB testing on Drupal 

### ISSUE THREAD

**Issue by jennpb** [wellcometrust/wellcomecollection.org#1294]
## Problem to be solved
In order to run any AB tests on current navigation, we need something in place on the Drupal site to allow for test deployment. Optimize or Optimizely free versions may be able to do this.

First test to run: Explore label

## Type
- Test

## Needs

- [ ] User research
- [ ] Analytics and/or component tracking

## Acceptance Criteria
- [ ] Need to be able to change labels on wc.org
- [ ] Need to be able to track and analyse use of B version

**Comment by jennpb** [comment]
Closed via https://github.com/wellcometrust/collection/pull/283
