### ISSUE TITLE
Redirect from wellcomeimages.org to new search

### ISSUE THREAD

**Issue by pollecuttn** [wellcometrust/wellcomecollection.org#1304]
## Problem to be solved
Ensuring that wellcomeimages.org visitors are redirected to the nearest/best place on wellcomecollection.org

**JPB update: We have a deadline of 6 November 2017 for a shutdown of wellcomeimages.org. All images need to be redirected from wi.org to wc.org by that time.** 

## TODO
- [x] Get a list of all pages that need to be redirected, and to where - @jennpb
- [x] Make sure wellcomeimageawards.org links are dealt with - @jennpb
- [x] Redirect https://wellcomeimages.org/indexplus/image/XXXXXXX.html to https://wellcomecollection.org/works?query=XXXXXXX
- [x] Redirect http://wellcomeimages.org/ixbin/imageserv?MIRO=xxxxxxxx to IIIF thumbnail
- [x] proxy pass /indexplus/lightbox.html?... to original site until it's switched off
- [ ] ~Update all links in Sierra (MARC 962 field) to https://wellcomecollection.org/works/XXXXXXX (May need Branwen to do a batch edit in Sierra if possible, with mapping from API <--> Sierra)~ 
- [x] Put Hotjar feedback on /works so we can capture anyone who hasn't found what they're looking for
- [x] Messaging on wc.org for visitors coming from a wc.org redirect
- [x] Begin tracking number of redirects
- [ ] Update cookies register to reflect redirect alert cookie
- UI changes 
- [x] #1739 
- [ ] #1707 
- [x] #1696 
- [x] #1692

**Comment by jennpb** [comment]
Timescales:
- #Platform team doing final MIRO data dump on 17 Oct - new index created
- New index behind feature flag
- Christy to check new index against rules w/c 23 Oct

**Comment by jennpb** [comment]
@jamesgorrie @gestchild @davidpmccormick 
Here's the list of redirects: https://docs.google.com/spreadsheets/d/1uC8Q2F97IXIvvDObqPAUCOisdnb5pc3m1bCOrTIOpJA/edit?usp=sharing

I'd like to direct most of the info pages and galleries to /works, but we'll need a way to lookup the WI number from a WI link and match it to the new /works/ID.

**Comment by pollecuttn** [comment]
Thumbnails:

Thumbnails on the catalogue and Encore show people the image and that an item has been digitised (so hopefully they don't request ad hoc digitisation unnecessarily).

Single thumbnail on a record
Catalogue: http://catalogue.wellcomelibrary.org/record=b1194272
Encore: http://search.wellcomelibrary.org/iii/encore/record/C__Rb1194272
Thumbnail link for both: http://wellcomeimages.org/ixbin/imageserv?MIRO=V0040906 
You can see the thumbnail link from the 'MARC' links on the records in the 962|e field|subfield

Multiple thumbnails on a record
Catalogue: http://catalogue.wellcomelibrary.org/record=b1310681
Encore: http://search.wellcomelibrary.org/iii/encore/record/C__Rb1310681
Thumbnail links for both:
https://wellcomeimages.org/indexplus/image/L0081519.html
https://wellcomeimages.org/indexplus/image/L0081721.html
https://wellcomeimages.org/indexplus/image/L0081633.html
https://wellcomeimages.org/indexplus/image/L0081636.html
You can see the multiple thumbnail links from the 'MARC' links on the records in the 962|e fields|subfields

Video and multiple thumbnails on a record
In this example the video thumbnail should not be redirected; the image thumbnails should be redirected
Catalogue: http://catalogue.wellcomelibrary.org/record=b1676817
Encore: http://search.wellcomelibrary.org/iii/encore/record/C__Rb1676817
Thumbnail links for both for images only:
https://wellcomeimages.org/indexplus/image/L0055183.html
https://wellcomeimages.org/indexplus/image/L0055182.html
https://wellcomeimages.org/indexplus/image/L0055184.html
etc

**Comment by jennpb** [comment]
@gestchild @davidpmccormick 
One more redirect spotted in the wild:

`https://wellcomecollection.org/what-we-do/wellcome-images` should go to `https://wellcomecollection.org/works`

**Comment by davidpmccormick** [comment]
- [x] re-route 'what-we-do/wellcome-images' to '/works' added to #1748 (https://github.com/wellcometrust/wellcomecollection.org/pull/1748/commits/d50ca11692a1c2507f50c9318212ee584692b177)

**Comment by pollecuttn** [comment]
Snagging list: https://docs.google.com/spreadsheets/d/1uC8Q2F97IXIvvDObqPAUCOisdnb5pc3m1bCOrTIOpJA/edit#gid=1808297378

**Comment by davidpmccormick** [comment]
All done!
