### ISSUE TITLE
Images: Search Landing for Beta Users Design

### ISSUE THREAD

**Issue by Heesoomoon** [wellcometrust/wellcomecollection.org#1337]
## Type
- ✨ Feature

## Needs
- [x] Design 

## Problem to be solved / User Story
**Clear on-boarding experience and guidance for the beta users**
When we go live with new image search, we would like to inform the beta users about our image collection and what they can do with the images.

## UI Requirements
- a search field where a user can enter keywords then takes to search results
- a tagline describing the search feature (e.g. Explore 53,000 Artworks and Photos)
- clear messaging on image license policy and a link to more information (Creative Commons).
- a link to Wellcome Images 
- suggested keywords to allow a user to explore the image collection

## Future Ideas
Explore different modules to provide more engaging ways to discover our image collection
- showcase the diverse set of artworks and photos using image thumbnails (e.g. Featured Image Galleries)
- display editorial contents promoting object images from exhibitions
- recently visited images

## Tasks
- [x] Finalize the design
- [x] Review the design with the team
- [x] Post the files on Onedrive

**Comment by Heesoomoon** [comment]
Here's the latest design mockup.
![searchlanding_m1](https://user-images.githubusercontent.com/29206031/29318401-c9affd60-81c7-11e7-91b0-23f89d01b81a.png)

**Comment by Heesoomoon** [comment]
Here's the link to the files.
https://wellcomecloud-my.sharepoint.com/personal/h_jennings_wellcome_ac_uk/_layouts/15/guestaccess.aspx?guestaccesstoken=1OqVIhcY9ovsb1W3%2bEqt%2bSZSdpZ8ToiBzXCEZ%2brwWAQ%3d&folderid=2_1331b651f4c5c41b881bb0ac1bde6bca4&rev=1
