### ISSUE TITLE
Audit and remove any unwanted tracking scripts

### ISSUE THREAD

**Issue by jennpb** [wellcometrust/wellcomecollection.org#1494]
## Type
🚑 Health report

While we don't have any formal rules (yet) about opt-in for data collection, we want to make sure we're not inheriting remarketing or tracking services from the Drupal site. 

In the first instance, we need to remove the quantserve script that was added in Aug 2016 by @alfraser86: https://github.com/wellcometrust/collection/commits/88185debb03a0d64d5e9b1d531c9b85ed09a0d34/www/sites/all/themes/col_base/template.php 

@derivadow says "We should probably also double check we haven't added any other scripts or web bugs over the years especially if they aren't documented on the cookie policy as there are legal implications."

**Comment by jamesgorrie** [comment]
On v2 we use:
* Google Analytics / Optimize (Optimize is part of Analytics)
  https://developers.google.com/analytics/devguides/collection/analyticsjs/cookie-usage
  https://github.com/wellcometrust/wellcomecollection.org/blob/master/server/views/partials/analytics.njk
*  Hotjar
  https://www.hotjar.com/privacy
  https://github.com/wellcometrust/wellcomecollection.org/blob/master/server/views/partials/hotjar.js.njk
* Sentry 
  https://sentry.io/privacy/
  https://github.com/wellcometrust/wellcomecollection.org/blob/master/server/views/partials/monitoring.njk
* Numerous WC_* cookies
  I'd like to have a poke around which ones exactly, but they change dependant on tests etc... I'm not sure if we can have a wildcard like this

__TODO:__
- [ ] Find out about wildcard policy
- [ ] Make page alerting users to this
- [ ] Potentially make page allowing opt-out with explanations as to why we use their info
