### ISSUE TITLE
Publish CGDSYL events from Prismic

### ISSUE THREAD

**Issue by jamesgorrie** [wellcometrust/wellcomecollection.org#1532]
# TODO

- [x] Make sure that the current model fits in with what the CGDSYL events need
- [x] Get content from the CGDSYL events into Prismic

# Done

- [x] [We have a cron job querying Prismic from Drupal to add snippeted content to list pages such as `events` on v1](https://github.com/wellcometrust/collection/pull/282)

- [x] The events model has been rudimentarily setup in [Prismic](https://github.com/wellcometrust/wellcomecollection-content-model/blob/master/prismic/custom-types/events.json) ([view in UI](https://wellcomecollection.prismic.io/documents~k=events&b=working&c=unclassified&l=en-gb/new-events*new/)), and [the content model](https://github.com/wellcometrust/wellcomecollection.org/blob/master/server/content-model/content-blocks.js#L42-L50)

- [x] [Some concerns around the current system have been spoke about and documented](https://slack-files.com/T0442CG7E-F64LXM6AV-32084d0f57). Most of the concerns have been around the current event categorisation and labelling. See below: <img width="850" alt="screen shot 2017-09-19 at 13 47 08" src="https://user-images.githubusercontent.com/31692/30595373-eedc4d0e-9d48-11e7-9c3a-02458932657d.png">

- [x] [The general design has been built](https://cardigan.wellcomecollection.org/components/detail/event-template.html)

**Comment by jennpb** [comment]
MEGA. Thanks @jamesgorrie

**Comment by jennpb** [comment]
Shared this with @Heesoomoon last week, but here's a really helpful commentary on the issues they had with the exhibitions/events content model from Drupal; I assume we're fixing these modelling problems? https://github.com/wellcometrust/wellcomecollection.org/issues/825

**Comment by Heesoomoon** [comment]
@jennpb @jamesgorrie and I think we have solution to address the event that's associated to multiple things. We introduced the concept of Programme for Youth and Access events. Therefore, we can display the type of programme and which exhibition or series it belongs to.
For example, an AD Tour for CGDSYL will list following tags.
Events, Access Events, Part of: Can Graphic Design Save Your Life
And the type of the event (e.g. Audio described tour) will be displayed above the event title. 
https://wellcomecollection.org/preview/events/WdOizycAAF2cTGmN

**Comment by jamesgorrie** [comment]
@jennpb agreeing with @Heesoomoon the model we've adopted is requirements based (we need a team to contact? Add a contact team. We have programmes, add programmes).

**Comment by jennpb** [comment]
Sounds good to me!
