### ISSUE TITLE
Event Template Design Review

### ISSUE THREAD

**Issue by Heesoomoon** [wellcometrust/wellcomecollection.org#1609]
## Objective
Meet with the events team to review content and design

## Tasks
- [x] Meet with James to ensure event content & design aligns with current content model
- [x] Meet with Access events team (Orla)
- [x] Meet with General Public events team (Natalie, Val)
- [x] Meet with Library events team (Danny, Ross)
- [x] Meet with Youth events team (Catherine Ayres)
- [x] Summarise findings and update design

**Comment by Heesoomoon** [comment]
Feedback from Access events team
- Need to consider for general events with accessibility 
- Provide more prominence to the booking type (Drop in, Ticketed)
- Provide clear messaging for first come/first serve
- Prefer to include the access type (BSL, AD, STT) in the event title

**Comment by Heesoomoon** [comment]
Feedback from General Public event team (Natalie and Val)
- Reading room events will continue to be announced on the day of the event onsite and won't be publicised on the website
- Would like to review event types (Heesoo to send current list)
- Location is useful. However, it needs to be optional since they may not have the info upfront.
- Not sure about displaying the pricing up front. Explore different treatment.
- Would like to see some guidelines around optimal amount and content for event summary and description.
- Booking T&C should be either displayed on the page or easy to access
- Access to past events and the media can be useful for giving visitors what to expect from an event. 
- Some events have Facebook page and need to include a link
- What's on newsletter will cover more general updates. Need to follow up about the long term plan of the newsletter strategy.

**Comment by Heesoomoon** [comment]
@jamesgorrie Here are the updated version of Youth, Access and General Public events based on our conversation.
![event_mobile_access](https://user-images.githubusercontent.com/29206031/31282978-1ba6d05a-aaac-11e7-8ddc-617ff1a008d2.png)
![event_mobile_public](https://user-images.githubusercontent.com/29206031/31282980-1bb71dac-aaac-11e7-8988-90fe173673cf.png)
![event_mobile_youth2](https://user-images.githubusercontent.com/29206031/31282979-1bb5dcda-aaac-11e7-94fa-c992f81713af.png)
![event_mobile_youth1](https://user-images.githubusercontent.com/29206031/31282981-1bd16b94-aaac-11e7-8345-ff2ff9894c16.png)

**Comment by Heesoomoon** [comment]
@jamesgorrie One thing to consider. Long content makes it harder to discover 'Enquire to Book' CTA especially on mobile. I wonder whether we can explore ways to display the button on the bottom like the sticky nav on digital stories.

**Comment by jamesgorrie** [comment]
@Heesoomoon Or have it at places that are natural i.e. after integral info etc.
Sticky is a bad experience for anyone with a shorter mobile.

**Comment by Heesoomoon** [comment]
@jamesgorrie Let's assess the location of the CTA with the current content as is and define the integral info. FYI, Eventbrite uses sticky button.
![eventbrite](https://user-images.githubusercontent.com/29206031/31320166-deda8a3c-ac67-11e7-80d5-c41d90099518.png)

**Comment by Heesoomoon** [comment]
Feedback from Youth Programme team
- 2 types of events: School events which need to be booked by the teacher (Study day) and Youth events 
- Events are announced in 3 months chunks (15 Study day, 3 Saturday studio and additional student events)
- Announce through email and social media
- Potentially need to separate into two different event types (School Programme and Youth Programme) and consider revisiting the booking info copy
- Need to support ways to display fully booked flag for individual event
- Separate email newsletter for School and Youth programme

**Comment by Heesoomoon** [comment]
Feedback from Library team (Danny and Ross)
- Library Insights events are publicised online
- Library Seminar events will not be promoted online and continue to be emailed to the partner organisations. 
- No library specific newsletter
