### ISSUE TITLE
PP: Setup Hotjar Poll on CGDSYL Events 

### ISSUE THREAD

**Issue by Heesoomoon** [wellcometrust/wellcomecollection.org#1729]
## Type
- 🚑 Health report

## Objectives
To capture user feedback on Events template
- Did they find the information needed to attend the event?
- Are they satisfied with the experience? 

## Tasks
- [ ] Finalise the poll questions
- [ ] Setup the poll on Hotjar
- [ ] Review with @jennpb
