### ISSUE TITLE
WC.org Site Audit

### ISSUE THREAD

**Issue by Heesoomoon** [wellcometrust/wellcomecollection.org#1745]
## Type
UX discovery

## Objectives
To document current WC.org and WL.org for the navigation user research and project planning.

## Tasks
- [x] Audit of current site and identify which pages need to be revisited or merged
- [ ] Review with the team
- [ ] Create the materials for the card sorting exercise

**Comment by jennpb** [comment]
[DrupalContent27102017.xlsx](https://github.com/wellcometrust/wellcomecollection.org/files/1418689/DrupalContent27102017.xlsx)

**Comment by pollecuttn** [comment]
@jamesgorrie was looking at 404s showing up in GA for .aspx pages (from Drupal's predecessor?). Noting here in case looking at / sorting out these 404s fits with the site audit work
