### ISSUE TITLE
Event UI & model

### ISSUE THREAD

**Issue by jennpb** [wellcometrust/wellcomecollection.org#1790]
## Type
- ✨ Feature
This epic includes the things we want to work on in order to move away from using Drupal to Prismic. 

## Why?
- To support Events team on uploading next season events by 23 November
- So that we can support the operational needs of the Events team, through ticketing and event statuses
- So that we make improvements based on user research and usability recommendations, especially for mobile
- So we don't have to run tests against two platforms
- So the content contributors don't have to duplicate effort
- So we can make contributor workflows better

## Release 1
- Core event information: Date, Time, Ticketing Info, Booking Info, Location, Booking Status, People involved
- Event booking supported via Eventbrite
- Booking statuses dynamically generated
- Events ticket info shown in context
- Structured metadata in place so Google can deal with it
- Transition over to PP team 

## To Do
- [x] Review booking information for events template
- [ ] Document content model

## Metrics to monitor / Success
Have number of bookings increased/decreased?
Have no-shows increased?
Scroll depth
Can you find an event in Google and see the date and time?
Usability testing demonstrates no significant usability problems

**Comment by Heesoomoon** [comment]
Project planning
https://trello.com/b/UcKSpaMe/projectplanningpublicprogram-nov-2017

Next step:
Project kickoff to discuss the scope of work
Follow up with the Events team with the decision

**Comment by jamesgorrie** [comment]
re: Model
Note from Nat Coe, events could potentially have multiple formats in 1 event.
The example given was Film Screen & Discussion.

Potential thought for the model:
```JSON
{
  "schedule": [{
    "format": "film screening",
    "dateRange": {
      "start" "2017-01-01T13:00:00",
      "end" "2017-01-01T15:00:00"
    }
  }, {
    "format": "discussion",
    "dateRange": {
      "start" "2017-01-01T15:15:00",
      "end" "2017-01-01T16:15:00"
    }
  }]
}
```

**Comment by jamesgorrie** [comment]
Another question is around broadcast media.
I'll assume we just have that as part of the associated media block (still needs work).

**Comment by jamesgorrie** [comment]
Example eventbrite event:
https://www.eventbrite.co.uk/e/haitian-vodou-ritual-dance-workshop-tickets-40144900478?ref=estw

**Comment by jamesgorrie** [comment]
@jennpb @Heesoomoon 

Taken from @Heesoomoon's IA doc below, the algorithm for showing extra information (information in the event info box at the bottom) is as follows:

* If the event is ticketed
  > Please be aware that booking a ticket for a free event does not guarantee you place. Admission is on a first come, first serve basis for ticket holders.

* If the event is Drop in and is at an event with capacity<sup>1</sup>:
  > First come, first served from the Information Point on level 0. Please be aware that tickets can run out if we are busy. Doors open 15 minutes prior to the event starting.

* If the event is a STT Tour:
  > This event is for visitors who are deaf, deafened, and hard-of-hearing.
              For more information please email us at
              <a href="mailto:access@wellcomecollection.org">access@wellcomecollection.org</a>
              or call 020 7611 222

* If the event is an AD Tour:
  > This event is for visitors who are TODO: Content.
              For more information please email us at
              <a href="mailto:access@wellcomecollection.org">access@wellcomecollection.org</a>
              or call 020 7611 222

* If the event is an BSL Tour:
  > This event is for visitors who are TODO: Content.
              For more information please email us at
              <a href="mailto:access@wellcomecollection.org">access@wellcomecollection.org</a>
              or call 020 7611 222

* If an access option attached to the events (STT / BSL / AD) has a description<sup>2</sup>, show that. e.g.
  > This event will have live speech-to-text transcription for visitors who are deaf, deafened and hard-of-hearing.

From what I can see there are a few content jobs here:

- [ ] "This event is for visitors who..." for BSL and AD tours (<= the language here seems quite excluding? I can't find it on the site somewhere, but it was on the doc)

-[ ] Descriptions for BSL and AD access options

<sup>1</sup> This requires us to know which locations have limited capacity, and to attach them to the event. I know we've decided to not show initially, but it seems like a really good idea to have the metadata, as we can then attach photos etc depending on what floor the location is and what facilities we have to surface at a later date.

<sup>2</sup> This could also be used to explain to people that a workshop might suggest a certain amount of participation from people etc.

We still need to figure out if the educational events have any structure to this information or if it's just free text.

![eventtype](https://user-images.githubusercontent.com/31692/33706052-986769de-db2a-11e7-887f-b1d79dd8f08b.png)

**Comment by Heesoomoon** [comment]
@jamesgorrie Re: the content copy, let's try to work with Orla and Jen S. to make it concise and clear. 

Here's the current copy used for access specific events. 
AD: Georgia is trained in audio description techniques by VocalEyes and has designed this tour for visitors who are blind or partially sighted.
STT: Visitor Experience Assistant Elissavet has designed this STT tour for visitors who are deaf or hard of hearing.
BSL: Our Visitor Experience Assistant Rob, together with interpreter Joanna McCaul, has designed this tour specifically for British Sign Language users.

Since we will display the people separately, we can come up with more generic one per access event type. 'This [access event type/format] event is designed for visitors who are [access needs]'. Let's confirm with Orla on how explicit we should be with the messaging.

**Comment by jamesgorrie** [comment]
@Heesoomoon When we are adding information about what a person has contributed to an event, I wonder if we'll have to work out how to combine this with the contributors...

**Comment by jamesgorrie** [comment]
I've just re-read this - I misunderstood.
We can definitely use the language above - it seems a bit more personable?

**Comment by Heesoomoon** [comment]
@jamesgorrie here's the placeholder copy for access events. I'll send to Orla for her review.
**Access Tour**
AD Tour: This Audio Described tour is designed for visitors who are blind or partially sighted. For more information, email us at access@wellcomecollection.org or call 020 7611 2222.
BSL Tour: This tour is designed for British Sign Language users. For more information, email us at access@wellcomecollection.org or call 020 7611 2222.
STT Tour: This Speech-to-text tour is designed for visitors who are deaf or hard of hearing. For more information, email us at access@wellcomecollection.org or call 020 7611 2222.

**Public Event with Access Option, Ticketed & Drop-in**
AD: This event will be audio described for visitors who are blind or partially sighted. For more information, email us at access@wellcomecollection.org or call 020 7611 2222.
BSL: This event will be British Sign Language interpreted. For more information, email us at access@wellcomecollection.org or call 020 7611 2222.
STT: This event will have live speech-to-text transcription for visitors who are deaf, deafened and hard-of-hearing. For more information, email us at access@wellcomecollection.org or call 020 7611 2222.

**Comment by jamesgorrie** [comment]
__TODO__
- [x] Single time Eventbrite ticket integration
- [ ] multi-time Eventbrite ticket integration
- [ ] Create some events with Public programmes team

**Comment by jamesgorrie** [comment]
![eventtype](https://user-images.githubusercontent.com/31692/34678400-f0775110-f48a-11e7-8f91-ae38eeda49b4.png)

I've reflected the more abstract concepts of the model that we've built into the view, helping us move away from defining the content to defining the content model.

A few things came up, namely:
* __Booking type___ is programatic and dependant on other factors of the event, the logic is stated in the document.
* __Event format and access options have been decoupled__ after a chat with @davidpmccormick and @gestchild this seemed to make the most sense. This means that if an event is of the STT Tour format, we require an editor to add the STT access option. This is to retain a more pure model. The hope is that if we gain more control over our CMS UI we could do this automatically while retaining the data integrity.

**Comment by jamesgorrie** [comment]
Thing to note, the current system considers the following the same thing:
![screen shot 2018-01-09 at 16 47 50](https://user-images.githubusercontent.com/31692/34732339-e9a405e0-f55c-11e7-94dd-77ae86ad6bf0.png)

**Comment by jamesgorrie** [comment]
## Questions to ask the model
* What does it look like for an editor to create this?
* Could it be extended with some new, made up values?
* What does a useful query look like for
  * people who would like to see BSL / AD / STT events only
  * people who want to see school events only
  * people who want to see discussions with BSL interpretations
  * workshops designed for young people

## Definitions
__Format__
What the audience or participant might expect from the event structure and their level of participation.

__Access options__
What options have we supplied to create a higher level of access.

__Intended Audiences / Designed for__
Who is the event designed for.

__Interpretations__
In which way will I be able to absorb the content of the event, and is it the primary way?

## Evolution 1: Formats and access options
__Formats__
* BSL Tour
* STT Tour
* AD Tour
* Discussion
* Workshop
* Study day
* Walking tours
* Youth events
* School events

__Access options__
* BSL
* STT
* AD

---

## Evolution 2: Formats, access options, and IA / DF<sup>*</sup>
__Formats__
* BSL Tour
* STT Tour
* AD Tour
* Discussion
* Workshop
* Study day
* Walking tours

__Access options__
* BSL
* STT
* AD

__Audiences__
* Schools
* Youth

## Evolution 2.1: Formats, access options, and IA / DF
__Formats__
* Tour
* Discussion
* Workshop
* Study day
* Walking tours

__Access options__
* BSL
* STT
* AD

__Audiences__
* Schools
* Youth
* BSL Speakers
* Deaf or hard of hearing
* Blind or partially sited

---

## Evolution 3: Formats, interpretations, and IA / DF
__Formats__
* Tour
* Discussion
* Workshop
* Study day
* Walking tours

__Interpretations__
* BSL
* STT
* AD

__Audiences__
* Schools
* Youth

---

## Evolution 3.1: Formats, interpretations (with primary selectable), and IA
__Formats__
* Tour
* Discussion
* Workshop
* Study day
* Walking tours

__Interpretations (with primary selectable)__
* BSL
* STT
* AD

__Audiences__
* Schools
* Youth

<sup>*</sup>Intended audiences, designed for. Designed for is the language and process we use, and remains inclusive.

**Comment by jamesgorrie** [comment]
@jennpb could we consider this closed in favour of smaller tasks e.g 
https://github.com/wellcometrust/wellcomecollection.org/issues/2053
