### ISSUE TITLE
Events list page

### ISSUE THREAD

**Issue by jamesgorrie** [wellcometrust/wellcomecollection.org#1934]
Build the events list page.
So far we have: https://wellcomecollection.org/events

## Acceptance Criteria
- [x] Lists future events
- [x] Links to past events on Drupal (R1)

## TODO
- [x] Force `16:9` images
- [ ] Eventbrite ticket information (@jennpb <= is this acceptance or next steps?)

**Comment by jennpb** [comment]
@jamesgorrie Do you mean the live event ticket status (Booking opens date, Fully booked)?

**Comment by jamesgorrie** [comment]
@jennpb Indeed I do.

**Comment by jennpb** [comment]
Let's call it next steps, then. 

Acceptance Criteria for live ticket status can be covered separately:
- promo should update with live status
- event page should updated with live status.

**Comment by jamesgorrie** [comment]
@jennpb Currently we show the ticket status on the event page.
We don't on the listings page yet - so could we consider this done?
