### ISSUE TITLE
Event series: design page for event lifecycle

### ISSUE THREAD

**Issue by jennpb** [wellcometrust/wellcomecollection.org#2327]
## Type
✨ Feature

## Value
- Makes it clear whether an event in a series is upcoming or past
- Makes it clear when there are no upcoming events in this series
- Gives an onward journey to event outputs, e.g. podcast

## Recommendations
- List fixed set of past events to provide impression of the event series.
- Display all upcoming events and display 'No upcoming events' messaging if there are no upcoming events.
- Include a link to output e.g. Podcast for Packed Lunch series 

https://www.notion.so/wellcometrust/Events_Past-Events-cc2ff44298dd471dab4bbba7d74ac6f1

## To Do
- [x] Get copy for 'no upcoming events' (Jen S.) #2355 
- [x] Follow up with @silveroliver on how we want to reflect event outputs in the domain model
- [x] Follow up with the events team regarding the branding and logo (Saturday Studio, Packed Lunch, etc.)
- [x] Sketch wireframe @Heesoomoon 

## To Do Visual Design
- [x] Follow up with the brand team about background pattern 
- [x] Update the template to match the design on Event schedule: background and page grid #2357
- [ ] Create promo link for 'What's on' and 'Podcast' #2356 
- [x] Create promo for past events (include as part of Promo system discovery) #2354

**Comment by jennpb** [comment]
@Heesoomoon I propose we close this because of the work happening on headers, unless you have a good reason to keep it open?

**Comment by Heesoomoon** [comment]
Sounds like a plan.
