### ISSUE TITLE
Newsletter signup

### ISSUE THREAD

**Issue by jennpb** [wellcometrust/wellcomecollection.org#2431]
## Type
✨ Feature

We need to rebuild the newsletter signup module by 25 May 2018 in order to comply with GDPR. This brings with it an opportunity to:
- get regular updates to people who want them
- expose all of the newsletters Wellcome Collection produces
- pare back the amount of data we collect from people and store.

Some work has already been done on other Wellcome sites, with approval from the Legal team. 

Here are the flow diagrams from Ulf:

- Subscribe flow: https://docs.google.com/drawings/d/1TBdIlWqNHCE0J3Pbvx3-UqebBBOQZ5RW3dgTpbX_6J8/edit?usp=sharing

- Unsubscribe flow: https://docs.google.com/drawings/d/1foph2w3SmuEc2domGxOi9Nf1n5nr_K-KPHacmyUztzE/edit?usp=sharing 

- Sync Dotmailer/Care: https://docs.google.com/drawings/d/1paQdOVuHaRPplhHM532ZC-Y6BuH142gQzNRqAAh0dhY/edit?usp=sharing

And here's an example of the wording that has been implemented (and approved by Legal):
![image](https://user-images.githubusercontent.com/1446139/38245900-e5ad2468-3737-11e8-96a0-23cf5ccad04e.png)

## Q+A
**What data to collect?**
Email address only

**How should we handle sample email?**
Out of scope for now. If we want to provide sample newsletters, we should work out how to automatically show the most recent, as newsletter content may take a different direction from newsletter to newsletter.

## Ready to release when...
- User can see promo to signup page
- User can get info about newsletters on a signup page
- User can select one or more newsletters
- User can confirm subscription
- User can unsubscribe from any/all newsletters via email and Dotmailer preference center
- Whole flow has been tested by us
- Tracking allows us to monitor signup page views  - set up as a goal in GA so we can monitor drop-offs? **(to be discussed)**
- Tracking sign up to multiple newsletters?

## What does success look like? 
- More signups over time (source: Dotmailer) - @hthair 

## Out of scope
- Providing a link to a sample newsletter
- Promos for individual newsletters

## To Do
- [x] Verify which newsletter groups still go out via Dotmailer (and check their title/branding) @jennpb
- [x] Draft copy for signup page - @jennpb and Jen S
- [x] Draft copy for preferences page - @jennpb and Jen S
- [x] See how we might use Dotmailer to track number of signups - @hthair 
- [x] See how we might use Dotmailer to track number of unsubscribes - @hthair 
- [x] Check to see whether any improvements can be made to the confirmation email by subscribing to a newsletter that has already had the GDPR treatment (e.g. wellcome.ac.uk)
- [x] Find out whether there's a separate confirmation per newsletter or whether we can have a single confirmation for all boxes ticked: single confirmation for all boxes ticked
- [x] Customise dotmailer email - @wellcometrust/experience-dev 
- [x] Kickoff 

## TODO dev
- [x] set up child account
- [x] customise email templates (confirm/unsubscribe-resubscribe)
- [ ] customise preference centre (enter email / options)
- [x] remove TEST - from address book - move into child account
- [ ] extra data fields that are useful for Linda? (speak to Dipak) (ACTIVITY-VALUE / CONSENT? / SOURCE)
- [x] run Linda through
- [x] sign up form copy finalised
- [x] newsletter promo
- [x] move required campaigns/templates across to WC child account
- [x] update footer text on campaigns / templates (no email unsubscribe etc.)
- [x] reporting
- [x] transfer account ownership to Rachel Collins / add other users

**Comment by jamesgorrie** [comment]
- [ ] Need to get address book ID from Linda

**Comment by Heesoomoon** [comment]
Newsletter Flow and Wireframe
[WC_Newsletter.pdf](https://github.com/wellcometrust/wellcomecollection.org/files/1991696/WC_Newsletter.pdf)

**Comment by jennpb** [comment]
Still need to customise the Dotmailer preference centre - will fill in requirements here

**Comment by pollecuttn** [comment]
From @jennpb:
We need to establish a way to ensure that our newsletter signup is performing well. We could measure this by tracking over time
-	Number of subscribers (to make sure people are subscribing as our user base grows)
-	Number of unsubscribers (indicative of interest in the content, but also if people are able to unsubscribe easily)
-	Drop-offs in subscribe flow. Could do this by setting up the Subscription Success page as a goal?

**Comment by davidpmccormick** [comment]
The links in campaigns are also presumably tracked?

**Comment by hthair** [comment]
I've also set up recordings for sessions with the newsletter sign up page so we can observe how people interact with the page. Once these have finished I'll watch them to get a better overall insight and then report back. 
As for number of sign ups, I'll talk to comms to find out how they check this.

**Comment by hthair** [comment]
Within Dotmailer they have a graph that shows number of new contacts and total contacts. We can pull the figures from here. We'll just have to ignore the first few days of data (and the first month on the overview) as all previous users were imported in in one go. I can report on the sign up numbers as part of the monthly reporting, and set a reminder to check it weekly.

**Comment by jamesgorrie** [comment]
In favour of #2692
