### ISSUE TITLE
Image galleries

### ISSUE THREAD

**Issue by jamesgorrie** [wellcometrust/wellcomecollection.org#2460]
Problem statement (From @jennpb):

Image galleries/image lists are a way that we can use images to tell and/or support a narrative.
We observe that there may be different requirements depending on where the list appears and what it is being used for.

How can we improve our image list components so that:
- they work well on mobile
- they aren't constrained to an 'article' context (e.g. has author and timestamp when Article; doesn't have author and timestamp when it's a gallery to support an exhibition, facility, etc)
- image caption and related narrative are clearly defined

Places where image galleries/lists appear:
- Exhibitions/Installations/Other facilities in venue
- Standalone article
- Supporting an article (inline or modal component)

Relates to #1554 

Notes from chat with content team:
* Portrait & Landscape rules should be based on viewport
* Should probably remove the `imageList` type and stick to `imageGallery` model
* Which looks like this ![untitled drawing 1](https://user-images.githubusercontent.com/31692/38494491-06da9eee-3bee-11e8-8b6a-54a454d977cd.jpg)
* 1 image gallery, multiple layouts, e.g. `featured`, `horizontal`, `vertical`? Ot the potential to use the current weight system e.g.
  * `featured` = at top, instead of featured image, but with the author above it
  * `standalone` = within the article, but vertical scrolly, or potentially the "Click to view this image gallery in glorious fullscreen mode"
  * `default` = as it stands (hopefully improved).
  * We should get the stats on image galleries

**Comment by jennpb** [comment]
Not sure there's any user story here, but here's a problem statement:

Image galleries/image lists are a way that we can use images to tell and/or support a narrative.
We observe that there may be different requirements depending on where the list appears and what it is being used for.

How can we improve our image list components so that:
- they work well on mobile
- they aren't constrained to an 'article' context (e.g. has author and timestamp when Article; doesn't have author and timestamp when it's a gallery to support an exhibition, facility, etc)
- image caption and related narrative are clearly defined

Places where image galleries/lists appear:
- Exhibitions/Installations/Other facilities in venue
- Standalone article
- Supporting an article (inline or modal component)

**Comment by jamesgorrie** [comment]
@jennpb superb - I moved it into the main body of the ticket as it seemed more important.

**Comment by jennpb** [comment]
Possibly helpful editorial requirements/rules:
- Caption should be around 50-75 words
- No headings in lieu of image titles
- No need for a featured image if it's a standalone gallery
- Need to be able to see whole image in viewport

**Comment by jennpb** [comment]
## TODO
- [ ] Analyse component tracking so we don't repeat things that aren't working now
- [ ] Analyse scroll depth on vertical 'article' galleries and horizontal inline galleries
- [ ] Analyse CTR to exhibition highlights from exhibition pages @hthair

**Comment by jamesgorrie** [comment]
- [ ] Think of 404 tests e.g. "Expand this gallery"

**Comment by hthair** [comment]
Exhibition highlights CTR:

**Comment by hthair** [comment]
scroll depth:
* vertical image gallery (ayurvedic man highlights page) -> 
- 25% scroll depth = 90% of pageviews
- 50% scroll depth = 86% pageviews
- 75% scroll depth = 80% pageviews
-100% scroll depth = 63% pageviews

* vertical image gallery (top ten creepiest objects in the collection) -> 
- 25% SD = 92% pageviews
- 50% SD = 89% pageviews
- 75% SD = 85% pageviews
- 100% SD = 68% pageviews

**Comment by hthair** [comment]
Horizontal image galleries:
The art of glassblowing -> 12% of the time the page was viewing the end of the image gallery was reached.
Picturing mental health -> 19% got to end of image gallery
You know the drill -> 7%
Book design -> 16%

**Comment by jennpb** [comment]
Notes from 13/14 September here: https://www.notion.so/wellcometrust/Image-galleries-Sep-2018-392a0aade54d440da735aec983332bd1

**Comment by jamesgorrie** [comment]
See all notes, design and PRs to do with the smashing new ✨ image list
https://github.com/wellcometrust/wellcomecollection.org/pull/3414
