### ISSUE TITLE
Interim homepage

### ISSUE THREAD

**Issue by jennpb** [wellcometrust/wellcomecollection.org#2621]
## Type
✨ Feature

## Purpose of interim homepage
Provide BAU view of what's happening so we can provide onward journeys into the v2 site

**Why is it interim?**
We don't know yet what kind of homepage will be better for our users. By doing an interim homepage as part of the Drupal migration, we can get ourselves onto a single platform, making it easier for us to test options. 

## Scope
header (assuming no major changes)
body 
footer (assuming no major changes)

Out of scope:
subnav
site search

## Who's it for?
People who come to our website and want to know what WC is all about
Us - to help us get traffic flowing through new site

## Discussion

**Header**
- where does WC strapline fit? 'the free museum and library for the incurably curious'

**Body**
- what body contains: promos for current exhibitions, articles (Installation and events?)
- promo scale and sizing (visual design: as is or update?)
- is this a today or this week view?
- how to promote marketing-led content, other non-current content (books, shop)
- how Content team can control the homepage - to what extent are some components dynamic or curated?
- how to deal with news-y things (defining CTA vs info promo)
- reusing Explore components
- rules and logic - number of items
- how do we override dynamic lists? 
- do we have content team do a weekly homepage refresh? 
- can we explore 'Visit us' module to showcase the physical space and display practical info?

**Footer**
- whether there are any key content pages that need to be added to footer (e.g. Accessibility, Venue hire, Contact us email address, etc.)

**Technical**
- SEO 
- Page loading - animation, movement? 
- Redirect? DNS changes?
- page performance - set threshold so we can monitor it

**Measuring usage + success**
- does homepage drive traffic to content? CTR
- CTR from Google/Search to site
- how can we track CTR based on position? heatmaps, something else?
- if we do next 7 days list, how do items drop off? 

**How do we know when we're done?**
- We have a page made of promos that link to live content

**Testing**
- test new homepage behind a feature flag (so we're nearly ready to push it out)

__TODO__

- [ ] Review what we know about current homepage performance - stats and high-level insights @jennpb

**Comment by hthair** [comment]
In terms of tracking CTR based on position --> (assuming heatmaps record properly which there have been issues with on homepage in the past), we'd need to start and end them before any promos are moved or changed position. I think a better bet might be to look at the CTRs using GA and compare the positioning (rather than the content of the promo) 
Just spoke to @jamesgorrie about this and there's a way to do this in GA so we can see how many CTs a promo got and it's position in the list.

**Comment by pollecuttn** [comment]
# First
- [ ] Finish promos - design
- [ ] What's-on style promos for today + next 6 days - build, then integrate finished promos
- [ ] Redirects for migration and to help home page work

Nav and footer don't change

# Next
- [ ] Measuring position on page of what gets clicked
- [ ] Strapline - design, then build
- [ ] Quicklinks/tabs - design, then build

**Comment by jamesgorrie** [comment]
# Dev list

# First iteration
- [ ] Create homepage route
- [ ] Serve homepage that is essentially whats-on
- [ ] Add articles component (we can use the async search results and give it `type:articles type:webcomics`)

# Second iteration
See results from first iteration.

**Comment by jennpb** [comment]
> In terms of tracking CTR based on position --> (assuming heatmaps record properly which there have been issues with on homepage in the past), we'd need to start and end them before any promos are moved or changed position. I think a better bet might be to look at the CTRs using GA and compare the positioning (rather than the content of the promo)
Just spoke to @jamesgorrie about this and there's a way to do this in GA so we can see how many CTs a promo got and it's position in the list.

@hthair @jamesgorrie does anything need to be implemented or is it just a matter of poking the GA?

**Comment by hthair** [comment]
@jennpb @jamesgorrie I think some changes need to be made in GA to a secondary dimension. Referral state?

**Comment by jennpb** [comment]
Test ideas moved to Notion board for now.

**Comment by jamesgorrie** [comment]
@hthair - we can track this - worth sitting down and showing.
