### ISSUE TITLE
Books: VD/UX enhancements

### ISSUE THREAD

**Issue by jennpb** [wellcometrust/wellcomecollection.org#2827]
## Type
- ✨ Feature

This is to implement visual design and UX enhancements post-migration.

## TODO
- [x] Add 'Books' tag as per rest of site (black tag), to enable linking back to index page
- [ ] Styling on subtitle and author
- [x] Styling for reviews
- [x] Rationalise contributor module: visual design, component header
- [ ] Linking contributor(s) #2695 
- [ ] Sizing of featured image
- [ ] Sizing of images on books index page
- [x] Get bios and headshots for authors not already in the system from Content

**Comment by jamesgorrie** [comment]
Viz > VD?

**Comment by jamesgorrie** [comment]
>  Sizing of featured image

Not sure we have anything left on that?

>  Rationalise contributor module
>  Linking contributor(s) #2695

I've moved these over to #2828

**Comment by jennpb** [comment]
@wellcometrust/experience-dev @Heesoomoon @GarethOrmerod 
Books pages in Prismic allow quotes and reviews, but we don't currently display them. Could we discuss componentizing this template and getting the quote styles visible?

**Comment by jennpb** [comment]
@wellcometrust/experience-dev 
Hm, they've magically appeared!
![screenshot 2018-11-29 at 07 46 21](https://user-images.githubusercontent.com/1446139/49206740-e5c9d600-f3aa-11e8-8b69-958e7d10e476.png)
