### ISSUE TITLE
Migrate Exhibition to Base Page

### ISSUE THREAD

**Issue by Heesoomoon** [wellcometrust/wellcomecollection.org#3009]
## Components
**Primary Content (everything you need for decision making)**
- [x] Header
- [x] Free tag
- [x] Feature image: fixed width with pattern background (needs discussion on how it scales to different views)
- [x] Feature text
- [x] Review quote(s) - could have multiple reviews
- [x] Body text
- [x] Contributors?
- [x] ~~Exhibition highlight~~ - leaving as is
- [x] Installations
- [x] Visit info module: group all visit related info in the yellow background - including opening times at the bottom, expanded by default

**Secondary Content (things to do without visit)**
- [x] Read and explore: part of Promo project https://github.com/wellcometrust/wellcomecollection.org/issues/3014 / relationships discussion (see TODO below on relationships)

**Onward Journey (other things to do at Wellcome)**
- [x] ~Try these next~ This will be part of onward journeys across the site

Tick = in design system and available on base page

## Exhibition Migration Plan (from the team meeting 14 Aug)
![migration_exhibition](https://user-images.githubusercontent.com/29206031/44103963-7ff1649c-9fe5-11e8-9788-2f21ca17e70a.jpeg)

## Next Steps
- [x] @GarethOrmerod to create 2 mockups (everything and common scenario)
- [x] Follow up with Jen S. on few issues raised during the team meeting

## TODO (dev)
- [x] Create relationships between exhibitions and events of the exhibition
- [x] Create relationships between exhibitions and article about the exhibition
- [x] Render the above

**Comment by pollecuttn** [comment]
Related: https://github.com/wellcometrust/wellcomecollection.org/issues/2816

**Comment by Heesoomoon** [comment]
## Exhibition Migration Plan (from the team meeting 14 Aug)
![migration_exhibition](https://user-images.githubusercontent.com/29206031/44103963-7ff1649c-9fe5-11e8-9788-2f21ca17e70a.jpeg)

**Comment by Heesoomoon** [comment]
@jennpb @jamesgorrie @GarethOrmerod I've updated the components list based on the content hierarchy we discussed last week. Feel free to update.

**Comment by Heesoomoon** [comment]
Here's the latest scope for the exhibition template. The headlines are tbd. Need input from the content team.
![img_4674](https://user-images.githubusercontent.com/29206031/45410770-7aede600-b66a-11e8-8844-4b6277894865.jpeg)

**Comment by Heesoomoon** [comment]
Refer to #3327

**Comment by Heesoomoon** [comment]
@GarethOrmerod Should we move 'Free' label to same spot as Events?
![screenshot-content wellcomecollection org-2018 09 17-13-11-04](https://user-images.githubusercontent.com/29206031/45622330-8a5e9c00-ba7b-11e8-86ed-297dcfc655e1.png)

**Comment by GarethOrmerod** [comment]
Yes, I think we should move it back up to the top. 

We were trying a different position having removed the nav divider, but in the header consolidatrion work I put it back in tbd

**Comment by Heesoomoon** [comment]
Need to update 'Access at Wellcome' link to 'All our accessibility services' per Jen's recommendations.

**Comment by Heesoomoon** [comment]
Two more things to resolve before going live.
- missing 'Free' label on the header
- add vertical spacing between components https://zpl.io/bJv1exW 
Q: Is this something we can apply globally? It would be useful for other templates (i.e. Events) to group information and provide right information hierarchy.

**Comment by jamesgorrie** [comment]
@Heesoomoon see #3419 for spacing issue
