### ISSUE TITLE
Design system: promo development

### ISSUE THREAD

**Issue by pollecuttn** [wellcometrust/wellcomecollection.org#3014]
## Who it's for
People who want to get an overall understanding of what they can do here and how it's all connected

## Problems to be solved
- Dead ends: there's nowhere to go from any page of content
- Cookie cutter approach to content cards means we can't express scale of a thing, whether it's a big exhibition, a small one, a regular event or a mega-event, a single article or a series.
- No way of bundling cards together
- Lack of definition - we get confused when we talk about cards and promos!
- Content team can't create a curated path to related content

## TODO
- [ ] Design exploration
- [ ] Present to team for design review and comments
- [ ] Promos for all media objects
- [ ] Document in cardigan

**Comment by jennpb** [comment]
Closing a duplicate issue #2521 - @jamesgorrie wrote up an April meeting (with some comments from Tom) https://github.com/orgs/wellcometrust/teams/experience/discussions/6

We've moved on quite a bit from this.

**Comment by jennpb** [comment]
This will be broken down into smaller tickets based on card/promo type:

#3097 S/M/L Cards
