### ISSUE TITLE
Migrate Event schedule

### ISSUE THREAD

**Issue by pollecuttn** [wellcometrust/wellcomecollection.org#3089]
## Who's it for?
Us.

## Problem to be solved
Moving from the article template to the base page so it can use all components consistently across the whole site.

## Done when
- Components available to include in Prismic

## out of scope
Page redesign, ie design enhancements that aren't urgent but 'nice to have'

## Components
- [x] Event schedule

Other components should be covered by events already migrated to base page https://github.com/wellcometrust/wellcomecollection.org/issues/3022

## TODO:
- [ ] Revisit how we display ticketing type info and location #3202 
- [x] Update event format label to use new `LabelsList` #3189 
- [x] Update order of components to Contributors, Dates, Schedule #3189
- [x] Hide ticketing and booking info for past events #3185 
- [x] Support multiple images
- [x] Update date & time format (favour #3008)
- [x] Ability for the content team to customise 'Need to know' info #3053 (see #3180)

**Comment by gestchild** [comment]
@pollecuttn this has already been done. I think @Heesoomoon might want to make some design changes at some point but it currently looks like this:

![localhost_3003_events_wuyf9ciaafl-3pk8](https://user-images.githubusercontent.com/6051896/43529438-33a063c8-95a3-11e8-9822-ee1e4d574956.png)

**Comment by Heesoomoon** [comment]
@pollecuttn @gestchild 
We should consider following
- Support multiple images
- Update date & time format (as part of #3008)
- Revisit how we display ticketing type info and location
- Update event format label
- Remove 'dates' 
- Ability for the content team to customise 'Need to know' info

**Comment by pollecuttn** [comment]
I'm putting this back in to do for page migration in light of @Heesoomoon's comments
