### ISSUE TITLE
Event schedule

### ISSUE THREAD

**Issue by jamesgorrie** [wellcometrust/wellcomecollection.org#3341]
# Blockers / questions

- [x] What happens with the ticket CTA once it goes live? Does the widget open up or does the user have to click through to see full event details? Has this been demonstrated?
- [x] ~~Need to suppress the redundant/empty info box at bottom of event~~ Won't fix now - see JPB comment
- [x] Need to suppress Just Turn Up (whatever that status flag is called) when each individual scheduled event has its own status #3351 
- [x] Full event details link when there are no additional details - what was the decision with this? #3349 
- [x] Need to allow users to go back to the Main Event from a sub-event. I suggest we need to model scheduled events as 'Part of [Event]' and include in the header as per the design system #3355
- [x] Dates list: shows 18:00 as the time. This is misleading. #3352 

# Enhancements (can wait til later)
- https://github.com/wellcometrust/wellcomecollection.org/issues/3008 - Where we have consecutive dates in the same month, the style should be 18-21 October 2018
- Use location icon in schedule to signpost locations
-  Make it easier to navigate date ranges on a multidate schedule (I think the dates get lost in the list so has the potential to be very confusing when people are trying to find out what is happening on a specific date)
-  I know Heesoo is concerned about the order of the Contributors and the schedule, but I suggest we try to do some testing on this before trying to make this change. It may be that by solving the problem of date navigation, we can make it easier for users to skip past the contributors.

**Comment by jamesgorrie** [comment]
> Need to suppress the redundant/empty info box at bottom of event

@jennpb This is easy enough to do  - do we not want a link to the Ts and Cs though?

**Comment by Heesoomoon** [comment]
@jamesgorrie re: T&C, you may be right. Since we are providing ticketing inline, it will be good to keep it. Also, we may want to provide general festival-wide information in 'Need to know' section i.e. location (building wide) and accessibility info. Is this something the content team can insert as applicable?

**Comment by Heesoomoon** [comment]
@jennpb Here's the update on Event Schedule Booking. James confirmed the eventbrite widget is implemented in the event schedule. It was just broken. I've documented two different models. Since Event Schedule used to have the booking CTA on the page, we think it may be best to keep the eventbrite widget on the page for now and test it against the other model which directs user to the event page to make a booking. 
![eventschedulebooking](https://user-images.githubusercontent.com/29206031/45764121-e23b0580-bc29-11e8-8d73-5c96df01b5c7.png)

**Comment by jennpb** [comment]
@Heesoomoon @wellcometrust/experience-dev @hthair How will we test it? Are we going to A/B it?

**Comment by Heesoomoon** [comment]
@jamesgorrie What's the latest on 'Just turn up' status for individual events in the Schedule listing?

**Comment by jamesgorrie** [comment]
@Heesoomoon unsure, I thought there was design conversations going on about it?

**Comment by jamesgorrie** [comment]
@jennpb We're open for business again?

**Comment by Heesoomoon** [comment]
@jamesgorrie In terms of the design, we like to introduce 'Messaging' pattern described in #3354. Should we go ahead and implement? It should apply to 'Just turn up' and 'Booking opens' messaging.

**Comment by jennpb** [comment]
@jamesgorrie I can't think why I would have reopened it. I'd suggest #3354 is it's own issue and will close this one again.
