### ISSUE TITLE
Search and /works test plan

### ISSUE THREAD

**Issue by jennpb** [wellcometrust/wellcomecollection.org#3693]
# Purpose
Plan out how we're going to test our work with users (internal or external) in order to establish a usability baseline and then to test iteratively.

## In scope
Usability testing /works pages as they are now 
Incoming Sierra metadata: info hierarchy, comprehension, does it help user accomplish goal? 

## TODO
- [x] Plan out research activities and team responsibilities (@hthair @Heesoomoon and Lyndsay)
- [x] Decide how to recruit participants for each research activity
- [x] Communicate test plan to rest of team / create new issues for research activities

**Comment by Heesoomoon** [comment]
Here are some research candidates for Works to set us in the right design direction.
- Ordering and grouping of the data fields (card sorting)
- Testing comprehension level for Sentence display ([Cooper Hewitt](https://collection.cooperhewitt.org/objects/18423451/)) vs. List display ([Harvard Art Museum](https://www.harvardartmuseums.org/collections/object/201597?position=1))
- Collecting user feedback on [Work type](https://github.com/wellcometrust/platform/blob/master/ontologies/Reference%20data/sierra-material-types.csv) labels

**Comment by hthair** [comment]
1) new usability test on works with external pps.
2) internal relevance testing booked for w/c 10th dec. 
3) card sort online for ranking order of info on works pages. 

new tickets being created to reflect above.
