### ISSUE TITLE
V2 Metadata Audit for Images

### ISSUE THREAD

**Issue by Heesoomoon** [wellcometrust/wellcomecollection.org#3698]
## Purpose
Review incoming Sierra metadata for Images and make recommendations for testing #3693 

## In scope
info hierarchy and grouping, rewording, any data clean up 

## TODO
- [x] Review Work ID Definitions
- [x] Review Item examples
- [x] Review with Silver
- [x] Make recommendations

## Audit
https://docs.google.com/spreadsheets/d/1ZLoPOnVBpNS40gYjCfTcp_M-YaEALkTkEoAWvxQr3sA/edit?usp=sharing

**Comment by Heesoomoon** [comment]
## Concepts
![wc_v2 metadata audit - concept](https://user-images.githubusercontent.com/29206031/48424845-77a2d380-e75b-11e8-9c27-a6ab6c6f8250.png)

**Comment by Heesoomoon** [comment]
[WC_V2 MetaData Audit - Concept1.pdf](https://github.com/wellcometrust/wellcomecollection.org/files/2580019/WC_V2.MetaData.Audit.-.Concept1.pdf)
[WC_V2 MetaData Audit - Concept2.pdf](https://github.com/wellcometrust/wellcomecollection.org/files/2580020/WC_V2.MetaData.Audit.-.Concept2.pdf)

**Comment by Heesoomoon** [comment]
**Update from the meeting with Silver**
For Silver
- Review Work Type and Genre with Experience team
- Cover SubFields in the domain model meeting
- Share the list of data fields that may be useful for Works

For Experience Team
- Analysis of 'Title' fields length
- Analysis of most commonly catalogued fields

Update V2 @gestchild 
- Group 'Physical description', 'Extent' and 'Dimension' fields as a single component 
- Display 'Production' data as a single component (Places, Agents, Date) 
- Remove link from 'Dimension'
- Remove 'Type' field
