### ISSUE TITLE
Works: Grouping and ordering of details

### ISSUE THREAD

**Issue by jamesgorrie** [wellcometrust/wellcomecollection.org#3954]
## Who it's for
- Users who are selecting materials for their research
- Users who are comparing different materials and evaluate the information 
- Returning users trying to retrieve the material they've viewed previously 

## The problem to be solved
The current grouping and ordering of the work details are not necessarily clear and easy to use for users who are comparing different items and evaluating information. 

## User story
As a user looking for materials to use for a project, I want the information about an object to be clear so that I
- understand this is a quality source
- can quickly see whether it's for me

As a user returning to retrieve information from the item I've viewed previously, I want it to be easy to locate information on the page.

## As measured by...
User Testing: qualitative feedback
Feedback mechanism: collect any missing info or other issues?

## Acceptance criteria: we are right if...
We collect feedback that suggests so

## Considerations 
- Clear grouping and ordering of information (visual design, spacing)
- Present the object info in a more engaging way (typography)
- Explore tag style
- Provide contextual help to explain things in plain language
- How to represent missing data

## Resources
- Meta Data Optimal Sort Ranking #3761
- API Data audit #3776 
- [Works Page GA Data](https://datastudio.google.com/reporting/1tYm-THYsahULRq_en341tGAVI94QBYBF/page/ZdTS)

## To-do
- [ ] Explore  different concepts 
- [ ] Protype in code
- [ ] User testing
- [x] GA Data: usage on Works page

**Comment by Heesoomoon** [comment]
Current grouping and ordering based on the group work from 22 January.

**What it is (Header)**
- Title
- Format/Genre
- Author/Creator (from contributor info)
- Date (from production info)
- Image (TBD)

**What it's about**
- Description
- Lettering

**How it looks**
- Physical Characteristic
- Dimension
- Extent

**How it's created**
- Contributor (author/creator)
- Production (agent, place, date)
- Language

**Part of**
- Subject
- Genre

**Identifiers**
- Reference number
- ISBN

**Comment by jamesgorrie** [comment]
Thoughts and potential next steps:
- Could we make @gestchild's design a bit more spaced like the design (but not the design)
- We need to work on the section heading, probably with the content team, and they need to be purposeful
- Figuring out next steps to get more feedback on this
- Gather metadata analysis of books #3996

**Comment by jennpb** [comment]
@Heesoomoon 

> How should we handle multi contributors in the header?> https://wellcomecollection.org/works/e8h4dngn?query=women%20health
> How to group format and genre visually? How to handle multiple genres?
>https://wellcomecollection.org/works/emwh6qts?query=women%20health

Gareth is exploring these in design

> And what happens when format and genre have the same value (e.g. Website)?
> https://wellcomecollection.org/works/b5tyczxr?query=women%20health

We will continue to use both, until we work through these with Collections Info

> How should we handle missing data? Do we display the section header?
> https://wellcomecollection.org/works/abzftpy4?query=genres%3A%22Lithographs.%22

I think missing data fields should be ignored. If we don't have the data, it doesn't necessarily mean it will ever be created (e.g. Lettering is a field that's only used on Pictures)

I handed over to @GarethOrmerod this page where I've relabeled sections (rather than in Question format) - happy to discuss and get into testing.


![workpagehierarchy](https://user-images.githubusercontent.com/1446139/51856478-b8a49000-2327-11e9-8083-b2a3361b2d9e.jpg)

**Comment by Heesoomoon** [comment]
@jennpb Makes sense. Definitely ready to test. And thanks for catching the 'status'. It's important information to display upfront. If the item is available in both places, should we just display both labels?

As for the 'Download' and 'Using this image' components, it will be something we will be exploring this week. Till then, should we keep them as is in the live site ('Download' below the header and 'Using...' at the bottom of the page)?

**Comment by jennpb** [comment]
Yes, we need to reflect that a thing might have multiple locations (online, in library). I imagine these would act as filters on search as well.

I think we have two statuses:
Permanent status (where the thing lives): Online, In library
Temporary status (on the item itself): Available, At digitisation, On holdshelf, 

The permanent status is the one I want to focus on now.

**Comment by jamesgorrie** [comment]
Maybe useful reference to the conversation, there are some books that have both physical and digital locations: https://github.com/wellcometrust/wellcomecollection.org/issues/4012

**Comment by jennpb** [comment]
/Users/phillibj/Downloads/IMG_1733.JPG
/Users/phillibj/Downloads/IMG_1734.JPG
/Users/phillibj/Downloads/IMG_1735.JPG

**Comment by jamesgorrie** [comment]
Closing as this is released for now, we should probably think of a feedback / measurement plan if we'd like to start iterating.

**Comment by jennpb** [comment]
![image](https://user-images.githubusercontent.com/1446139/52771795-c435cd80-302e-11e9-8214-93940a15ab0b.png)
![image](https://user-images.githubusercontent.com/1446139/52771826-de6fab80-302e-11e9-9e03-4070f1a0f9fa.png)
![image](https://user-images.githubusercontent.com/1446139/52771853-f0514e80-302e-11e9-875f-fb9c0a03ae01.png)

**Comment by jamesgorrie** [comment]
🥇 "The Viewing Zone" 🥇
