### ISSUE TITLE
Epic: Catalogue search Beta

### ISSUE THREAD

**Issue by jamesgorrie** [wellcometrust/wellcomecollection.org#3958]
We'd like to offer a beta catalogue search to allow users to search more of the catalogue, and for us to start looking at what features we will need to build to do this.

Be more than just an image search so we can get better and more useful feedback to inform how we improve search.

Near future things to look at:
- [ ] Open up search to include more results. The current filters allow us to open this up by `workType`([currently mapped from here](https://github.com/wellcometrust/platform/blob/master/catalogue_pipeline/transformer/transformer_sierra/src/main/resources/sierra-material-types.csv)), or what type of items are available. I am looking for an exhaustive list, but we have
  * `DigitalLocation`s: `iiif-image`, `iiif-presentation`
  * `PhysicalLocation`: https://github.com/wellcometrust/platform/blob/master/sbt_common/internal_model/src/main/resources/location-types.csv
- [ ] Display Online or In Library based on locations #4043 
- [x] Allow the search result / work card to support non-image work types #4148 
- [ ] For the above representation to be reflected in a work summary on the work page

Further future things to look at:
- [ ] Works with representation that aren't `iiif-image` i.e. `iiif-presentation`
- [ ] Iterations on the actions panel to support works that aren't `DigitalImages`
- [ ] Usage info
- [ ] Viewer

## Before first release with books added:
Navigation:
- [x] Images replaced by Collections

/works landing:
- [x] header: Explore our collections
- [x] Message is moved above search bar
- [x] Message updated for books
- [x] Search bar message changed to: 'Search for books and pictures' (ready in #4250)
- [x] Beta icon and 'More info' link to https://wellcomecollection.org/works/progress

Search results:
- [x] Digitised books discoverable
- [x] All / Books / Pictures filters added beneath search bar https://github.com/wellcometrust/wellcomecollection.org/issues/4226 https://github.com/wellcometrust/wellcomecollection.org/pull/4209
- [x] Beta banner https://github.com/wellcometrust/wellcomecollection.org/issues/3959

Work:
- [x] Preview https://github.com/wellcometrust/wellcomecollection.org/pull/4208
- [x] Non-js viewer https://github.com/wellcometrust/wellcomecollection.org/issues/4147
- [x] Beta banner https://github.com/wellcometrust/wellcomecollection.org/issues/3959
- [x] Find in library: wording change 'Where to find this'
- [x] Find in library: link to physical Wellcome copy
- [x] Find in library (non-Wellcome physical copy): display repository name https://wellcomecollection.org/works/x29tmhhr
- [x] non-Wellcome repositories: only display name of repository, not the logo
- [x] Preview: remove 'Share' above copy URL
- [x] Preview: send event to GA to track opening a digitised book
- [x] Viewer: back button to go back to work page
- [x] Viewer: change height to 90% of browser viewport
- [x] Viewer: provide alt text for the images in the viewer
- [x] Viewer: move navigation buttons to be side by side
- [x] Viewer: move title and Overview link to between nav and viewer
- [x] Viewer: truncate title to a single line at any width
- [x] Viewer: use responsive images

Download:
- [x] Single images can be downloaded
- [x] Download book PDF (dlcs.io) https://github.com/wellcometrust/wellcomecollection.org/issues/4228

Comms:
- [ ] Release notes updated https://wellcomecollection.org/works/progress
- [x] Jenn to have talked with Collections teams

**Comment by jamesgorrie** [comment]
Closing as split into smaller pieces or complete
