### ISSUE TITLE
Digitised content: download options

### ISSUE THREAD

**Issue by jennpb** [wellcometrust/wellcomecollection.org#4084]
## Who it's for
People who want to do something with our digitised content off of our site.

## Problem to be solved
We don't really know which file formats and types of things people would find most helpful to download. Research needed!

**Details and user stories to be filled in later - these are merely notes for now**

Single images:
- full size / large
- small size / 760px - this is the only pixel dimension we can know

Multiple images:
- whole work (PDF) - currently in UV contains cover sheet with bibliographic citation info
- raw text (TXT)
- selected images (JPG)

MOH reports:
- all the above plus:
- whole borough collections as ZIP
- CSV of all tables / select tables
- raw text of some or all

## Questions
- Analytics #4076 
- ways of collecting and filing data on personal devices
- download whole work as... ?
- downloading single images in a multi-image work?

## User Story/Job

In order to
 _(why? accomplish a goal/get a benefit)_

As a
 _(who? user/persona)_

I need/want/expect
_(what? to do this thing)_

## Acceptance Criteria

- [ ] The interface should do this thing
- [ ] and this thing
- [ ] and this thing.

**Comment by jennpb** [comment]
May have insights in Aurelius

- What are the insights?
- Do we know enough? What else do we want to find out?

**Comment by Elltie** [comment]
@jennpb  All comments now in Aurelius and insights made with supporting statements.
