### ISSUE TITLE
More feedback from users & be more than an image search

### ISSUE THREAD

**Issue by jamesgorrie** [wellcometrust/wellcomecollection.org#4134]
## Aim
Be more than an image search and get more feedback from people.

## Option
* Add books (available online only) to our search
* Open up entire API

## P1, work to be done
- [x] Book preview #4145
- [x] MVP Book viewer #4147
- [x] Feedback form content #3740
- [x] Interface for filter and feedback prompt (TBD)
- [x] Search result redesign to account for no thumbnail. #4148. Can be released before other work (includes icons). Should probably be released as A/B to check that result follows don’t go down

## P2, work to be done
This hasn't been explored yet.

# Notes
The piece that is a little scary in terms of time is the MVP Book viewer. It’s a piece of string that is potentially very long, but quite nicely, after talking to Tom C, this could be really interesting: https://canvas-panel.digirati.com/styleguide/#canvasprovider

(“Minimum viable viewer” has too much emphasis on “M”)

---

All of the above are suggestions and thoughts on the aims setup by @jennpb of getting more feedback and being more than an image search. 

We could probably break these down into smaller tickets, but thought I would just jot down some thoughts, discussions, and work that is already in the pipe line.

# Feedback and analytics
* [Beta programme opt-in](https://github.com/wellcometrust/wellcomecollection.org/issues/3959)
* [User Feedback mechanism](https://github.com/wellcometrust/wellcomecollection.org/issues/3740)
* https://github.com/wellcometrust/wellcomecollection.org/pull/4133
* https://github.com/wellcometrust/wellcomecollection.org/issues/4110#issuecomment-463963056
* Look at the data points we had from the design sprint, and see if we want to start measuring those

# Opening up the API results
* Get books ready for testing with the public (remove the `Catalogue search filters` toggle)
  * [Allowing you to use filters for this, but maintaining the default as we currently have it](https://github.com/wellcometrust/wellcomecollection.org/pull/4133)
  * Better analysis of search, [e.g.](https://github.com/wellcometrust/wellcomecollection.org/issues/4110#issuecomment-463963056)
  * Having an online preview of a book
    * Look at ways of getting the manifest information onto the page performantly
  * Potentially a link to the viewer
    * Have a `/works/{id}/items` and put the V3 viewer on to see what we could be using from it?
  * Thinking how we might surface book titles as exact matches. An idea was to have a check if someone is searching for books, and see if the search term is particularly long (more than 3) and suggest something like "Looking for and exact match on __________" and link to the search query in `""`.

**Comment by jamesgorrie** [comment]
This has been broken into smaller tickets, or had the work complete
