### ISSUE TITLE
Usability session: works (preview and multiple work types)

### ISSUE THREAD

**Issue by hthair** [wellcometrust/wellcomecollection.org#4171]
### Aims/Purpose
In order to understand how people evaluate a multi-medium search result, we want to show users our latest designs and results to see how usable they are. 
- Test full research workflow: search > result > item > viewer > save/download
- Validate the usability of specific components: Work card, Header, Preview, CTA
- Investigate user needs on upcoming features: Viewer, Download book, Search filter, Beta, Feedback

As a researcher
I need/want/expect
to find all relevant materials around a search and be able to understand what type of items I'm viewing. (book, image etc)

### Tasks
- [x] Confirm recruitment 
- [x] Check with devs re build of thing to be tested and set deadline
- [x] pull out all possible research questions and add to ticket for review
- [x] Write script
- [x] Review script with Product Manager
- [ ] Pilot (optional)
- [x] Think about extras we could add in to the test
- [x] Update room booking
- [x] Send Bluejeans links to transcribers
- [x] Book testing room
- [x] Email Reception with participants' names
- [x] Check Bluejeans set up is working
- [x] Book viewing room
- [x] Email team with viewing room invite
- [x] Print consent forms/script
- [ ] Add link to script on Sharepoint to this issue
- [x] get payment vouchers ready

**Comment by hthair** [comment]
v1: single image preview
v2: multi image preview with scroll
v3: multi image preview static 

Research Questions:
search:
- Do they understand what material types are being displayed in the search results?
- what do they understand by 'books', 'digital images', and 'pictures'? (label comp)
- Do they know what actions they can take e.g. view item online
- what information are they looking for at this level?
- 'search our collections' what is their expectation?
- when a search returns hundreds of results what would they do next? How do they narrow or refine? How many results do they look through before refinement?


Work ID page:
- Goal: learn which preview (of the 3 we've designed) best helps them understand and evaluate item usefulness?
- what role does the preview serve for them? (size, what is shown, legibility, call to action, expectations)
- 'view online' CTA, what do they expect this to do? 
- how do researchers use digital surrogates? (from backlog)

Beta:
- In what way would they expect to provide feedback?
- what does 'beta' mean to them?

**Comment by hthair** [comment]
Insights deck: https://wellcomecloud.sharepoint.com/:p:/s/wcdigitalexperience/EdVLqEZU_-xIi-Rp7Geeff4B-lLIbn6zLwFUe3qnfHYVxw?e=1Nq7Us
