### ISSUE TITLE
Investigation: Request an item from closed stores

### ISSUE THREAD

**Issue by jennpb** [wellcometrust/wellcomecollection.org#4199]
## Who it's for
Library members and library staff who use their member number to request materials from closed stores.

## Background
The majority of our collections are held in closed stores. In order to view them in person, you need to have a library card and you have to go through the Request process via search.wellcomelibrary.org or catalogue.wellcomelibrary.org.

Do any services need to be built for online ordering of materials? What do we have access to already? 

## Tasks
Before we get started on this, there's some formative research that needs to happen in order to proceed:
- [x] Capture 'Request' workflow (UX - @Heesoomoon )
- [x] Identify any integration points/services, such as Access, Patron API, etc. @pollecuttn 
- [x] Dig up any/all research or flow diagrams on the Request > Retrieval process (LE&E, LSS) @pollecuttn 
- [x] Dig up any system diagrams showing end-to-end request process @pollecuttn 
- [x] Access to Circ rules @pollecuttn 
- [x] Any existing documentation relating to login (libsys, not SSO) @pollecuttn 
- [x] Set up test account(s) for devs @pollecuttn 
- [x] Getting live item status (Available, on holdshelf, due date, etc)
- [ ] User flow diagrams for ideal state

## Success measures
- Successfully process a closed stores request

**Comment by pollecuttn** [comment]
## Integration points/services
[Sierra REST API](https://techdocs.iii.com/sierraapi/Content/titlePage.htm)
"Operations
With the Sierra REST API, you can retrieve (GET) authority, bibliographic, branch, item, order, and patron data, including checkouts, fines, and holds. You can retrieve responses in JSON, XML, or for some endpoints, MARC-in-JSON. Query parameters constrain the result sets.

You can perform POST, PUT, and DELETE operations for hold data, and PUT updates to patron names, addresses, phone numbers, and emails. Most POST and PUT operations require request objects."
https://techdocs.iii.com/sierraapi/Content/zReference/operations.htm

## Research or flow diagrams on the Request > Retrieval process (LE&E, LSS)
There's not a diagram for the whole process, more that it's documentation for e.g. retrieving something from closed stores, or the journey the slips take

## Systems diagrams showing end-to-end request process
These don't exist

## Circ rules
Not needed: the relevant circ rule should kick in based on the patron type and the item type

## Documentation relating to login (libsys, not SSO)
Again, this doesn't exist

##  Getting live item status
Sierra REST API item object status: https://techdocs.iii.com/sierraapi/Content/zReference/objects/itemObjectDescription.htm

**Comment by pollecuttn** [comment]
@jennpb Preservation/Data teams need to change how they access the Sierra REST API to using a transit VPC (see https://github.com/wellcometrust/platform/issues/3570). @wellcometrust/experience-devs will also need to access the Sierra REST API via the the transit VPC too.

This work is in the [Preservation backlog](https://github.com/wellcometrust/platform/projects/9) and expected to be worked on at the beginning of June. This needs to be completed before Experience can use the Sierra REST API.

**Comment by jamesgorrie** [comment]
I imagine we could probably provide a proxy API to this so we don't have to deal with it directly.

**Comment by jennpb** [comment]
Initial investigation completed Q1 2019-20
