### ISSUE TITLE
User Research: Search & View

### ISSUE THREAD

**Issue by hthair** [wellcometrust/wellcomecollection.org#4210]
### Aims/Purpose

Validate new features: filters, preview, book viewer

As a researcher I want to be able to see everything you have on a topic area.
As a researcher I want to look at just what text results you have on something (not visual items)

### Research Q's:
Filters:
- How do researchers refine/narrow/change/adapt a search?
How do people understand the breadth of content available?
What others things do people want to filter by?

Preview on item page:
- What role does a preview serve for the user? (size, what is shown, legibility, call to action, expectations).
- What is useful when trying to evaluate if an item is relevant?

Reading view:
- How do researchers expect to view material online?

### Components/areas we have for testing are:
- beta label
- filters on search
- preview area on item page
- book viewer
- image credit (check comprehension on what we have)

### Tasks

- [ ] Confirm recruitment with recruiters
- [x] Check with devs re build of thing to be tested and set deadline
- [x] Write script
- [x] Review script with Product Manager
- [ ] Pilot (optional)
- [ ] Think about extras we could add in to the test
- [x] Update room booking
- [x] Send Bluejeans links to transcribers
- [x] Book testing room
- [x] Email Reception with participants' names
- [x] Check Bluejeans set up is working
- [x] Book viewing room
- [ ] Email team with viewing room invite
- [x] Print consent forms/script
- [ ] Add link to script on Sharepoint to this issue
- [x] payment vouchers

**Comment by hthair** [comment]
Insights stored in Aurelius. Main results: 
- beta label stood out but not everyone sure what this meant. Action: changed copy next to it to add context
- users would use filters to narrow by worktype, most still want to see everything you have to offer to begin with though.
- preview for book is useful in showing the user at a glance what the book might contain. Particularly useful to have index. Most click through quickly to view inside.
- Liked large viewer but want to be able to more quickly navigate through it to relevant areas by doing a search within text and having more thumbnails visible to jump more quickly.
