### ISSUE TITLE
User research: researcher trusted sources

### ISSUE THREAD

**Issue by hthair** [wellcometrust/wellcomecollection.org#4356]
### Aims/Purpose/research question

- How do researchers find recommended and new resources in their subject area? How do they decide whether it's reliable?

Interview session will cover questions on and around:
- how they choose which sources to use
- what they like or dislike about these
- frequency of engagement and when/what stage in the research process
- how do they know what to trust?
- feelings around wikipedia data
- show them alpha site and probe on features they find useful/not useful. 
- how do they stay up to date on their topic area?

### Tasks
- [x] Write script
- [x] Review script with Product Manager
- [ ] Pilot (optional)
- [x] Think about extras we could add in to the test
- [x] Update room booking
- [x] Send Bluejeans links to transcribers
- [x] Book testing room
- [x] Email Reception with participants' names
- [x] Check Bluejeans set up is working
- [x] Print consent forms/script
- [ ] Add link to script on Sharepoint to this issue

**Comment by hthair** [comment]
Link to script: https://wellcomecloud.sharepoint.com/:w:/s/wcdigitalexperience/EYKxrXKsJyBElk_nvV30zE8BcEbd0ZZcT9yxoDmWCNDnRQ?e=vngyS6
Results added to Aurelius. Will need more participants to get a more complete answer to the research questions.
