### ISSUE TITLE
User Research: Discovery & Guidance aka Mr Rogers

### ISSUE THREAD

**Issue by Heesoomoon** [wellcometrust/wellcomecollection.org#4395]
## Purpose
- How do we help the library visitors with onboarding and help to make them better researchers?
- How can we model the online experience based on the current library/research service we provide and make it better?
- Validate any gap in our research insights for non-academics/self-developers

## Key Research questions
TBD

## Research Plan
Task 1 Observe & interview library visitors using our collections
Task 2 In-depth interview with visitors using research library materials
Task 3 Library desk observation (LED and RMR)
Task 4 Interview external research specialist
Task 5 Workshop with internal research specialist
Task 6 Understanding our collections

## Deliverables
1. Build user profiles/update
- Who are they? What’s their motivation? Why are they using Wellcome?
- Current research experience and pain points
- Their needs and opportunities?
2. Update user stories based on findings
3. Guidance Map 

## Tasks
- [ ] Plan a workshop for Task 5

**Comment by jennpb** [comment]
# Outputs
- Revised profiles
- Visual user journey map
- Insights logged in Aurelius

# Comms plan

- [ ] Meet with content team to discuss research and implications for content development; kick off content audit
- [ ] JPB to present to teams once all outputs are available
