### ISSUE TITLE
Search query testing with external users

### ISSUE THREAD

**Issue by jennpb** [wellcometrust/wellcomecollection.org#4411]
# Who it's for
Data team - to get more feedback on search relevance
Users - to contribute to improving search quality

## Goal
Validate implicit test data 
https://github.com/wellcometrust/platform/issues/3662

# Problems to solve
- Low sample size
- Get more people providing **explicit feedback** on search results for general searching (e.g. keyword-based)
- Ensure that we're providing reliable results for the type of general searching that is in evidence at the short tail

# TODO / Ideas
- Establish research goal/questions
- Design a feedback mechanism for search results 
- Hook input into data capture mechanism
- Update release notes
- How do we invite users to participate?

# Questions
How do we know when we've hit the point of diminishing returns?

# UPDATE
We went with an explicit relevance ranker. Details below. Launched Nov 2019

**Comment by jamesgorrie** [comment]
We have been talking a lot about how we might start collecting feedback on relevance from our service outside of Wellcome Collection staff.

None of these have been decided on, but it feels like they would help us answer some questions around what is acceptable from a UX perspective, but get's us the data we need to start start iterating on relevance.

As part of this, it has been expressed that we don't think we will have the answer to relevance, but this will be a process of asking more questions to get closer to that.

## Requirements
- [ ] There is a metric needed for is we are not collecting explicit relevance data, and will infer it from CTR
- [ ] TBD

## Restrictions
- [ ] TBD

---

## Ideas so far

### A/B test query types
We could take `n%` of people and separate them into 4, and then start using one of the four custom `queryType`s for their search. We can use the CTR metric for this.

#### Considerations
- Would we be breaking the search for some people? This raises the bigger question around if we have this is beta, are we good to be testing things like this? 
- We could let people know that they're in a test, and allow them opt-out.
- Alternatively we could allow them to opt-in - but we get into the fuzzy definitions of what beta is and what people currently expect and should expect from the service at this stage, and what room we have for testing.

--- 

### Open up the query type selector to everyone
We open up the query type selector to more people.

#### Considerations
- We might need to give more explanation as to what the query types are, and what they could be used for
- @harrisonpim had the good point that what we currently have is probably not great. 
- It creates a feature that will be changing quite a lot dependant on feedback and analysis, so we might be creating things that are removed in a week, which might make some people angry if they liked it.

--- 

### Relevance rating
We could open up having a feedback mechanism the allows people to start rating generic search terms. [The mechanism has been built](https://github.com/wellcometrust/wellcomecollection.org/pull/4378), but we're missing the "in" to the feature. 

Some thoughts were:
- Having something on the landing page with a list of chosen terms explaining to people that we need their help. When they use these links the will be given the opportunity to rate the relevance of those terms.
- Having a switch that is always exposed that allows people to rate relevance
  ![screencast-localhost-3000-2019 04 29-16-19-00](https://user-images.githubusercontent.com/31692/56906696-b07cfd80-6a9a-11e9-9f57-b9a56d8616ee.gif)
- Some other CTAs on the landing page

**Comment by jennpb** [comment]
## Discussion on 14 June:
We decided we'd go forward with an explicit relevance ranker based on @jamesgorrie's PR #4526 

Users will launch the relevance ranker from 'Explorer' tags on /works landing page, on a 1-4 scale

## TODO

- [ ] Design 1-4 scale component
- [ ] Revisit Explorer component: design, topic examples
- [ ] Draft copy to invite users to participate
- [ ] Review copy with Content team
- [ ] Update Beta release notes

- [ ] Stacks post / invite participation
- [ ] Personal and Wellcome Collection/Library Twitters

**Comment by Heesoomoon** [comment]
Update 5 July
@jennpb @jamesgorrie 
Here are the workflow and wireframe for the Search Result Feedback module based on the team discussion on Tuesday. I've reviewed with @harrisonpim. I'll be meeting with @dannybirchall to bring him up to date and try to see if we can get help with the copy.

[SearchResultFeedback.pdf](https://github.com/wellcometrust/wellcomecollection.org/files/3362582/SearchResultFeedback.pdf)

**Comment by pollecuttn** [comment]
Design review 26 September:

- When user chooses to opt in or not from search results, save this info in a cookie for 1 year
- No invite to rating on /works landing; but have first invitation to rate in the list of search results
- Have opt in inline in first search result only
- Opt in message to have ratings stars on it to hint at what the user will get when they opt in
- Have opt out above the first search result

**Comment by jamesgorrie** [comment]
> Have opt in inline in first search result only

Not sure if I have misunderstood this - but do we mean the first work in a set of results, or the first time someone searches?

If the former, no questions.

If the latter - does it work that if it is your first search of that session, we show it, then not for the rest of the session? Or is it that if you do another search we are inferring that you have opted-out and then you are opted out for a year as per the explicit opt-out. Another option could just to have a explicit dismiss (which is essentially the opt-out).

**Comment by pollecuttn** [comment]
In the first work in a set of results. Thanks for helping to clarify this.

**Comment by pollecuttn** [comment]
Design review 3 October 2019:
- opt in inline in first search result only: felt this didn't work; have opt in above list of results
- capture all taps on ratings; only use final rating when analysing relevance ratings
- copy to be clear about what you're rating ie the relevance/usefulness of the result, not e.g. how much you like the image

**Comment by jennpb** [comment]
@harrisonpim @jamesgorrie in terms of indicating relevance in the UI, do these match your grading of 1 2 3 4?

1 star = Not relevant to my search
2 stars = A bit relevant
3 stars = Relevant
4 stars = Most relevant

@wellcometrust/weco-experience-devs This is the language I propose using, if it fits Harrison's metric.

**Comment by harrisonpim** [comment]
Happy with 1, 2, and 3, but I'd like to change 4 to something like 'Completely relevant' or 'Totally relevant'. People should know that they can assign 4 stars to more than one item, and 'Most' sounds quite absolute to me!

**Comment by pollecuttn** [comment]
@harrisonpim Do you have a different suggestion? Highly relevant? More relevant? Something else that would fit how it's being measured?

**Comment by harrisonpim** [comment]
yeah, 'Highly relevant' is fine by me 👍

**Comment by pollecuttn** [comment]
@GarethOrmerod Please put the link to the designs in zeplin on this issue

**Comment by pollecuttn** [comment]
22/10/19 NP asked *WCDigitalEditorial for feedback on copy

**Comment by dannybirchall** [comment]
Some comments on the words at the request of @pollecuttn:

The meaning of the stars 1-4 is self-evident; they don't need 'very/sightly' labels; the wording and consistency of calls to action are more important

There should be consistency across what you're asking users (which I think is: "how relevant is this individual result to the (your understanding of) the search you just did?")

Possession should be clear & consistent: it's 'your search' and 'your results', but 'our collections'.

'Rate this' next to the stars is slightly confusing, and there isn't consistency across different implementations  ('is this useful', 'rate this', etc) so I would ask like this, in ascending order of available space:

Relevant?
How relevant is this?
How relevant is this to your search?

On the wide purple banner, I would use the words:

Help us improve your search results
Rate your search results by how relevant they are to you
Rate your results | No thanks

On the browse (canned search?) test, I would use the words:
Discover our collection through these topics and rate their relevancy.

Think that's it! Let me know if I missed anything.

**Comment by GarethOrmerod** [comment]
A couple of observations for what is currently behind the toggle:

- The purple banner is too wide for the text, also the vertical alignment of the text needs adjusting
- The vertical alignment of the text after the stars also looks slightly off

![relevancy-rating](https://user-images.githubusercontent.com/36885440/69332708-228f7c80-0c4f-11ea-9905-813ecf840d43.png)

**Comment by gestchild** [comment]
@GarethOrmerod I've put in a PR to reduce the width of the purple banner.

The vertical spacing within the banner and the alignment of the text behind the stars is related to the issue we've discussed about using Helvetica Regular. When you turn off the helveticaRegular toggle the alignment is fine. This is a bigger issue that we need to address.

**Comment by pollecuttn** [comment]
@gestchild Jenn's happy for this to come out from behind the toggle. Can we get it out, please?
