### ISSUE TITLE
Viewer: viewing controls

### ISSUE THREAD

**Issue by jennpb** [wellcometrust/wellcomecollection.org#4442]
## Who it's for
Viewer users - to **control my viewing area**

## Problem to be solved
Need to provide ways of controlling the focussed view of a work by 
- zooming in and out to see detail
- switching into a 2-page view so researcher can see any marginalia that bridges both pages
- rotating a single page to make it easier to read content printed in different orientations

This functionality is feasible with OpenSeadragon 

CAVEAT about 2-page view: May not be wanted with non-book-shaped materials, e.g archives, loose manuscripts, anything printed but not-bound. Consider how configurable the viewer needs to be based on material type.

## Components
- [x] Zoom in/out
- [x] Rotate 90°
- [x] Single/double page toggle moved to #4533 

## TODO
- [x] Event tracking on components
- [x] Check page view event being sent
- [ ] Check download tracking being sent
- [x] Add tracking to detail view/view all toggle
- [x] Put tracking on all viewer controls (need for A/B testing on arrow controls)
- [x] Agree on visual design

## Acceptance criteria
- User can initiate zoom in/out
- User can rotate an image in 90° increments
- User can switch between a single page and a double-page view
- Double-page view must reflect book opening (Left and Right page, not Front and Back)

## Success?
TBD

**Comment by jennpb** [comment]
#4325

**Comment by Heesoomoon** [comment]
@jennpb During the viewer pop-up research, the majority of users prefer to see 2-page views for books or manuscripts. 
- provide much-needed context e.g. how it relates, discover any additional info
- clear understanding of the material type
- less click and visually less overwhelming

Based on those findings, we recommended displaying 2-page view in both list and detail views by default for relevant material types.

The current implementation display a single page view. Should I create a separate ticket as an enhancement?

**Comment by jennpb** [comment]
@Heesoomoon @pollecuttn Yes please, make the 2-page view a new ticket with label:improvement

There is some back-end logic we need to sort out to determine what gets displayed as a 2-page view
