### ISSUE TITLE
Thumbnail drawer

### ISSUE THREAD

**Issue by pollecuttn** [wellcometrust/wellcomecollection.org#4443]
From https://github.com/wellcometrust/wellcomecollection.org/issues/4325

## Who it's for
Users of the viewer who want an overview of multi-image works

## Problem to be solved
Users want an overview of a multi-image work

## Agreed
* Only 1 image = no thumbnail drawer
* More than 1 image = thumbnail drawer open when arrived at from preview
* Close on clicking 'x'
* Close when an image is selected
* Close when clicking on viewing area

## TODO
Do we need to consider?:
- [ ] Opening/closing animations for neurodiverse?
- [ ] Is the thumbnail drawer open when the view page is arrived at from search?
- [ ] Is the thumbnail drawer open when the view page is arrived at from a shared link?

## Acceptance criteria
- [ ] Thumbnail drawer opens and closes
- [ ] Thumbnail drawer closes via close 'x'
- [ ] Thumbnail drawer closes after image selection
- [ ] Thumbnail drawer closes when the focus area is clicked
- [ ] User can select thumbnail to update image in focus view
- [ ] Event tracking on opening/closing of thumbnail drawer
