### ISSUE TITLE
Relabel digitised books as Books, not E-Books

### ISSUE THREAD

**Issue by jennpb** [wellcometrust/wellcomecollection.org#4482]
## Who it's for
Collections researchers

## Problem to be solved
The workType label 'e-book' covers these actual types:
- Books that have been digitised
- PDFs (that may have a hard copy 'book' in the library)
- 'E-books' provided by third-party electronic resource providers, e.g. 18th Century Collections Online

'E-book' carries strong associations with Kindle or other epub readers, and this is confusing to users when what they see are scanned/photographed pages.

## TODO
- [ ] isolate our digitised books and label them 'Books'. These are identifiable because there is a IIIF manifest.
- [ ] Recommend change in API

## Acceptance Criteria
- [ ] Digitised books display 'Books' label in search results and on /work page
- [ ] Digitised books continue to use 'Electronic books' as subject heading (as this is part of the MARC record)
- [ ] Digitised books continue to filter as a Book

**Comment by jennpb** [comment]
@jamesgorrie @jtweed Is it best to attack this one from the API side first, or from the front-end?

**Comment by jennpb** [comment]
Talked to @jtweed about this. This should be handled in the API but first we need to ensure that we're correctly classifying things that are bundled into the e-book category:
- our own digitised books
- PDFs classified as books
- digitised books/manuscripts on other platforms, like EEBO (early english books online)

**Comment by jamesgorrie** [comment]
@jennpb It seems pretty clear what should be classified as books, could you add some info on what should be classified as `e-books`?

**Comment by jennpb** [comment]
https://github.com/wellcometrust/platform/issues/3863

**Comment by jamesgorrie** [comment]
We'll have this deployed shortly.
