### ISSUE TITLE
user research: viewer round 2 & date filters (23.05.19)

### ISSUE THREAD

**Issue by hthair** [wellcometrust/wellcomecollection.org#4493]
### Aims/Purpose
viewer:
- validate workflow with new design: overview (thumbnails) to double page view
- check understanding of new icons/all controls
- validate vertical scrolling across both views
- check assumptions for the information panel

date filters:
- how do people use date filters?

### Tasks
- [x] Check with devs re build of thing to be tested and set deadline
- [x] Write script
- [x] Review script with data team/UX
- [x] Pilot (optional)
- [x] Think about extras we could add in to the test
- [x] Update room booking
- [x] Send Bluejeans links to transcribers
- [x] Book testing room
- [x] Email Reception with participants' names
- [x] Check Bluejeans set up is working
- [x] Book viewing room
- [x] Email team with viewing room invite
- [x] Print consent forms/script
- [x] Add link to script on Sharepoint to this issue
- [x] print out observation answer sheet/email link to observers for transcription.

**Comment by hthair** [comment]
Link to script in sharepoint. Prompt questions aren't written down as it will depend on what they talk about but I will be prompting on what they think all the buttons do along with general feedback about the order of screens https://wellcomecloud.sharepoint.com/:w:/s/wcdigitalexperience/EfhKuhTk7pFEnyx6Mc3CWRMBY0K6vXCINNWuGxJGTnoHnw?e=JOoHRW

**Comment by hthair** [comment]
Only had 3 participants this week so will follow up again to gather more info on date search filters. I think we can do this with an online survey as most questions are checklist answers. It also means we can gather more data that will be useful as it's not the usual usability type test where we only need 5. 

insights so far:
- researchers know what date range they want to focus on usually near the start of the project/research
- alphabetical list of results when using date filters isn't all that helpful
- sorting chronologically (either oldest to newest for those looking at primary material, and newest to oldest for those looking for commentary on older works/later editions first) is useful
- when items have date estimates on them it's still useful to have them included in the results list rather than omitting them.
