### ISSUE TITLE
Visit us: content and layout update

### ISSUE THREAD

**Issue by Heesoomoon** [wellcometrust/wellcomecollection.org#4523]
## Who it's for
Venue visitors

## Problem to be solved
Content links on current '[Visit us](https://wellcomecollection.org/visit-us
)' page are quite flat making it difficult to highlight certain information. As part of the Access initiative, we want to
- Improve awareness of our Access services and other aspects of the building
- Make it more inviting and friendly using appropriate imagery and copy

## Initial Ideas
- Apply visual hierarchy to provide 'curated feel' of landing page using components available in the content page template
- Single access point for all useful information and links to plan a visit e.g. what's on

## Success measures

- Qual: Is it more welcoming?
- Qual: Quality of design / brand perception
- Quant: Scroll depth
- Top 10 pages from Visit Us should remain roughly the same (Caveats: We don't expect to drastically increase traffic to Accessibility, but we want to raise its profile. Opening Times and Getting Here may decrease due to brief info being displayed)

## To-do: First Iteration
- [x] Meet with Danny to gather information
- [x] Explore layout options
- [x] Meet with Danny to review the ideas 
- [x] Meet with the devs to go over the feasibility
- [x] analytics
- [x] @hthair to setup hotjar scroll map to monitor current usage
- [x] Build static page so we can monitor and test @wellcometrust/experience-devs 
- [x] @dannybirchall to review with his team and provide new copy and images
- [x] @gestchild to update the page and make it live
- [x] Setup Hotjar Heatmap for the updated page @jennpb 
- [x] Hotjar Heatmap Analysis

## Enhancements
- [x] @Heesoomoon to list out all potential use cases for 'Feature' promo https://www.notion.so/wellcometrust/Promo-System-1feac64c93204437b43caf7305c1e695
- [ ] @GarethOrmerod to explore 'Feature' promo concept to make a highlight 'Accessibility'
- [ ] @GarethOrmerod to explore additional Text link style to make it more prominent

**Comment by Heesoomoon** [comment]
12 June 
I've reviewed two different layout ideas with @dannybirchall. Agreed to move forward with 'Option 2'. 

**Option 1**
![Visit Us_Concept1](https://user-images.githubusercontent.com/29206031/59353961-07255a80-8d1c-11e9-982d-75dcb99e462f.png)

**Option 2**
![Visit Us_Concept2](https://user-images.githubusercontent.com/29206031/59353971-0d1b3b80-8d1c-11e9-91d7-d6719ed7f3e7.png)

**Comment by hthair** [comment]
**Analytics for visit us section for last 6 months (Dec 1st 2018-May 31st 2019)**

/visit-us pageviews = 132k (unique pageviews = 85k)
This was the 5th most popular page viewed in this time period. (and again 6th if ranked by unique pageviews), either way a very important page to our users.
- For mobile it was 6th most popular (55k)
- Desktop it as 4th (63k)

**Desktop**

Summary:
avg time on page = 21 seconds
9811 people landed on the visit us page
Bounce rate = 10%
13% of the people that view the visit us page leave from it.(at some point)

Navigation:
Most popular previous page = home
Most popular next pages = 
1) opening times (27%) 
OR 2) Getting here (18%) 
OR 3) what's on (15%)
OR 4)  home (6%)
OR 5) what we do (4%)
This suggests people are either looking for opening times and how to get here, or they've clicked on visit us but more in a browsing mode or it's not what they thought it would be as they're not then clicking through to pages within visit us.

**Mobile**
Summary:
avg time on page = 23 seconds
5856 (1%) people landed on the visit us page
Bounce rate = 11%
14% of the people that view the visit us page leave from it (at some point)

Navigation:
Most popular previous page = home
Most popular next pages = 
1) opening times (34%)
OR 2) Getting here (23%)
OR 3) home (7%)
OR 4) what's on (7%)
OR 5) Getting around the building (3%)
The above stats show the most popular next pages people view from visit us. It suggests most people on mobile navigate to visit us to discover opening times and information about how to get here. As with desktop, a smaller percentage of visitors are going to the home page or what's on. This could indicate a mistake in going to visit us when actually they wanted to know what we have to visit, OR it could be that the people that arrive on visit us then want to navigate to other parts of the site.

Key message: the majority of those who visit the visit us page go on to navigate to opening times and getting here. There is a small indication of some cross over between whats on and visit us.

*families page*
![Screen Shot 2019-06-14 at 15 16 27](https://user-images.githubusercontent.com/26549021/59515613-6b305600-8eb7-11e9-8ac5-d58c929e228b.png)


* group visits page*
![Screen Shot 2019-06-14 at 15 14 45](https://user-images.githubusercontent.com/26549021/59515534-3de3a800-8eb7-11e9-81a7-31582004b0bd.png)

* getting around page*
![Screen Shot 2019-06-14 at 15 17 32](https://user-images.githubusercontent.com/26549021/59515680-8e5b0580-8eb7-11e9-8a4d-b9553304ef5a.png)

**Comment by hthair** [comment]
across devices: traffic to /access from /visit-us = 0.47%
Desktop: 0.46%
Mobile: 0.49%

**Comment by hthair** [comment]
Overall top next pages:
<img width="567" alt="Screen Shot 2019-06-25 at 15 56 26" src="https://user-images.githubusercontent.com/26549021/60109233-e7e9ec80-9761-11e9-80e1-3bdc12f09f29.png">

**Comment by hthair** [comment]
Mobile and tablet top next pages: 
<img width="569" alt="Screen Shot 2019-06-25 at 15 58 46" src="https://user-images.githubusercontent.com/26549021/60109388-2d0e1e80-9762-11e9-8f4c-badfc6e6ab12.png">

Desktop top next pages:
<img width="571" alt="Screen Shot 2019-06-25 at 15 59 42" src="https://user-images.githubusercontent.com/26549021/60109449-457e3900-9762-11e9-8a27-abe93d20e34e.png">

**Comment by Heesoomoon** [comment]
28 June
Met with @gestchild and @dannybirchall to review the page in browser.
- Remove 'Free' from the hero image and replace with 'Free admission' either in the tagline or near opening times.
- Change 'Getting around the building' to 'Our building'.
- Add short description copy for each section.
- Danny to work with Hannah to find appropriate images for the hero and 'what's on'.

I've updated the next steps accordingly.

**Comment by Heesoomoon** [comment]
Here's the GA and Hotjar Data from current Visit us page (25 June to 1 July). We will compare the data once we collect enough page views on new Visit us.
[WC_VisitUs_Analytics_25June-1July.pdf](https://github.com/wellcometrust/wellcomecollection.org/files/3354751/WC_VisitUs_Analytics_25June-1July.pdf)

**Comment by jennpb** [comment]
**Scroll depth before change**
Heatmap ended 26/6/2019 / 2000 page views / Hotjar

Desktop
![image](https://user-images.githubusercontent.com/1446139/61124879-1248e300-a4a0-11e9-9c08-88887039e01d.png)

Mobile
![image](https://user-images.githubusercontent.com/1446139/61124914-2c82c100-a4a0-11e9-9e84-786edbccc978.png)

**Comment by jennpb** [comment]
Will use this data to compare 1 month usage: https://docs.google.com/spreadsheets/d/1htu79hypmBDWOiWP0Yqsvk8QJ-NYUquHAP7F-t_kOWs/edit?usp=sharing

Will analyse next batch from 12 Jul-11 Aug

**Comment by jennpb** [comment]
**Desktop v2**
![heatmap-4451505-scroll-desktop](https://user-images.githubusercontent.com/1446139/64327568-d7f15300-cfc3-11e9-86d5-51bb0615d6e3.jpg)

**Mobile v2**
![heatmap-4451505-scroll-phone](https://user-images.githubusercontent.com/1446139/64327571-d9bb1680-cfc3-11e9-8733-226b0eb8bc15.jpg)

**Comment by taceybadgerbrook** [comment]
Comparing 30-day periods July/Aug and Aug/Sept, the visit-us page has become more popular and the bounce rate has decreased, suggesting the page has increased in user value.  People are spending less time on the page, although this might be because of better signposting.

Users are slightly more likely to view the visit-us page on their desktop than on a mobile device (less than 1%.)

Analytics | 15/7/19   - 14/8/19 | 6/8/19   – 5/9/19
-- | -- | --
Most popular page | works | works
Popularity ranking of visit-us | 10 | 6
Avg time on page | 52 seconds | 49 seconds
Bounce rate | 13.0% | 11.5%
Total visit-us page views | 18,804 | 13,784
(% of total) | 2.7% | 2.0%
Unique visit-us page views | 13,784 | 14,419
(% of total) | 2.6% | 2.7%
Desktop: |   |  
Visit-us page views | 8,285 | 8,925
(% of total visit-us) | 44.1% | 47.5%
Unique visit-us page views | 6,405 | 6,606
(% of total visit-us) | 46.5% | 47.9%
Mobile: |   |  
Visit-us page views | 8,524 | 9,161
(% of total visit-us) | 45.3% | 48.7%
Unique visit-us page views | 6,100 | 6,472
(% of total visit-us) | 44.3% | 47.0%

Comparing top 10 pages shows the getting-here page is now in the top 10, suggesting the changes in the visit-us page have meant that users can find directions more easily.


Top 10   pages:  15/7/19 - 14/8/19 | Top 10   pages:  6/8/19 – 5/9/19
-- | --
Wellcome   Collection \| The free museum and library for the incurably curious | Wellcome   Collection \| The free museum and library for the incurably curious
Smoke   and Mirrors: The Psychology of Magic \| Wellcome Collection | Smoke   and Mirrors: The Psychology of Magic \| Wellcome Collection
Catalogue   search \| Wellcome Collection | What's   on \| Wellcome Collection
What's   on \| Wellcome Collection | Catalogue   search \| Wellcome Collection
Visit   us \| Wellcome Collection | Visit   us \| Wellcome Collection
Smoke   and Mirrors Live Performances \| Wellcome Collection | Opening   times \| Wellcome Collection
Opening   times \| Wellcome Collection | Smoke   and Mirrors Live Performances \| Wellcome Collection
Misbehaving   Bodies: Jo Spence and Oreet Ashery \| Wellcome Collection | Misbehaving   Bodies: Jo Spence and Oreet Ashery \| Wellcome Collection
Thousands   of years of women’s pain \| Wellcome Collection | Being   Human \| Wellcome Collection
Medical   manipulations and the history of physiotherapy \| Wellcome Collection | Getting here \| Wellcome Collection

**Comment by taceybadgerbrook** [comment]
Comparing 30-day periods June/July with July/Aug, the visit-us page has remained the 6th most-viewed page and the percentage of unique page views has increased very slightly (0.1%.)  The average time on the page has more than doubled, showing the page has increased in value to users but the bounce rate has increased.  This might be because of better signposting.

Users are 2% more likely to view the visit-us page on their desktop than on a mobile device.


Analytics | 13/6/19 - 13/7/19 | 14/7/19 – 13/8/19
-- | -- | --
Most popular page | works | works
Popularity ranking of visit-us | 6 | 6
Avg time on visit-us page | 22 seconds | 53 seconds
Bounce rate for visit-us | 8.3% | 12.9%
Total visit-us page views | 19,377 | 18,550
  | 3.0% | 2.7%
Unique visit-us page views | 12,081 | 13,643
  | 2.5% | 2.6%
Desktop: |   |  
Visit-us page views | 9,882 | 8,137
(% of total) | 51.0% | 42.0%
Unique visit-us page views | 6,115 | 6,299
(% of total) | 50.6% | 52.1%
Mobile: |   |  
Visit-us page views | 7,771 | 8,439
(% of total) | 40.1% | 43.6%
Unique visit-us page views | 4,953 | 6,070
(% of total) | 41.0% | 50.2%


Comparing top 10 pages shows the getting-here and what-we-do pages are no longer in the top 10.  While what-we-do has dropped to 14th place, getting-here isn’t even in the top 50 pages.  Adding colour to the link may help increase visibility.


Top 10 pages:  13/6/19 - 13/7/19 | Top 10 pages:  14/7/19 – 13/8/19
-- | --
Wellcome Collection \| The free museum and library for the incurably   curious | Wellcome Collection \| The free museum and library for the incurably   curious
Smoke and Mirrors: The Psychology of Magic \| Wellcome Collection | Smoke and Mirrors: The Psychology of Magic \| Wellcome Collection
Catalogue search \| Wellcome Collection | Catalogue search \| Wellcome Collection
What's on \| Wellcome Collection | What's on \| Wellcome Collection
Visit us \| Wellcome Collection | Visit us \| Wellcome Collection
Misbehaving Bodies: Jo Spence and Oreet Ashery \| Wellcome Collection | Smoke and Mirrors Live Performances \| Wellcome Collection
Opening times \| Wellcome Collection | Opening times \| Wellcome Collection
Smoke and Mirrors Live Performances \| Wellcome Collection | Misbehaving Bodies: Jo Spence and Oreet Ashery \| Wellcome Collection
Getting here \| Wellcome Collection | Thousands of years of women’s pain \| Wellcome Collection
What we do \| Wellcome Collection | Medical manipulations and the history of physiotherapy \| Wellcome   Collection

**Comment by jennpb** [comment]
No negative outcomes of changing the info hierarchy and page design.

More users getting directly to the info they need: Opening Times and Address
Scroll depth is healthy

We'll pick up the card styling and weighting in another ticket.
