### ISSUE TITLE
Video and audio player improvements

### ISSUE THREAD

**Issue by jennpb** [wellcometrust/wellcomecollection.org#4545]
## Who it's for
Researchers using digital audio or video from collections

## Problem to be solved
We currently render digital audio and video using the native browsers' players. The functionality differs from browser to browser, and there are accessibility issues that we can resolve on our side. We can also improve the UI by using our own designs, enhancing the design system.

## TODO
- [ ] Explore UI designs
- [ ] Investigate feasibility of generating wave forms
- [ ] Design for search results

## User Story/Job

In order to
 _(why? accomplish a goal/get a benefit)_

As a
 _(who? user/persona)_

I need/want/expect
_(what? to do this thing)_

## Acceptance Criteria TBC

- [ ] The interface should do this thing
- [ ] and this thing
- [ ] and this thing.

## Checklist
- [ ] Event tracking
- [ ] Mobile first
- [ ] Compliance with WCAG 2.1

**Comment by jennpb** [comment]
![image](https://user-images.githubusercontent.com/1446139/60026474-8b200080-9693-11e9-896b-a83d2936f787.png)
