### ISSUE TITLE
User Research: Discovery & Guidance_Library Enquiry

### ISSUE THREAD

**Issue by Heesoomoon** [wellcometrust/wellcomecollection.org#4579]
## Objectives
To document the workflow of online and offline library enquiry process based on the workshop with the library staffs (part of #4395)

## Tasks
- [x] Create a draft version of the enquiry journey map
- [x] Document common enquiry questions and responses given by the library staffs
- [x] Review with the team (Jenn, Ross, Alice, Phoebe, etc.)
- [x] Digitise the enquiry journey map and share with the Library team
- [x] Highlight key opportunity areas

**Comment by Heesoomoon** [comment]
Draft version of the enquiry journey map
![IMG_5403](https://user-images.githubusercontent.com/29206031/61040987-8cf2ff00-a3c9-11e9-83d3-46afae8f9820.JPG)
