### ISSUE TITLE
Request an item: Journey map

### ISSUE THREAD

**Issue by Heesoomoon** [wellcometrust/wellcomecollection.org#4582]
## Objectives
To document the current workflow of requesting an item online and in-library and highlight potential opportunities to improve the process for the users and internal team.
(part of #4199)

## Tasks
- [x] Interview @pollecuttn to understand current workflow
- [x] Observe manual request process and shadow library members
- [x] Collect existing user insight for online request experience
- [x] Sketch user journey map (draft)
- [x] Review user journey map with the team
- [x] Digitise the user journey map

**Comment by pollecuttn** [comment]
Notion documentation: https://www.notion.so/wellcometrust/4582-Online-Request-46f03c1e3b8143e99e3e17d2449697ce
