### ISSUE TITLE
User research: Filtering by dates

### ISSUE THREAD

**Issue by Heesoomoon** [wellcometrust/wellcomecollection.org#4632]
### Research Objectives
To understand how users use dates in their search process
- When and how do they use dates (pre/post search result)
- Date range type (by year, month, date, century, period, etc.)
- Their expectation of the sources with unknown/ambiguous dates

### Research Questions
- Background questions to identify researcher profile (novice, intermediate, expert)
- How do they use dates in their search process?
- What type of date range do they tend to use? (year, month, date, century, period, etc.)
- Which prototype meets their needs most? Why?
- Do they understand [date]?
- How do they expect to review the sources with unknown dates?
- Do they expect to refine further to smaller date range? (century > decade)
- Do they notice number of search results and pagination? How do they use it?

### Research Methods
- Popup research with working prototype #4631
- 5-10 minute interview in the viewing room in the library

### Tasks
- [x] Review the prototype with dev
- [x] Write script
- [ ] Review script with @jennpb 
- [x] Book testing room
- [x] Inform the library team about the research
- [x] Drink voucher
- [x] Conduct research
- [x] [Analyse results](https://www.notion.so/wellcometrust/4632-User-Research-Filtering-by-dates-e8b4fc8cad224080abaf6d56512613e7)
- [x] Share the findings with the team and make recommendations
