### ISSUE TITLE
User Research: Search Filter

### ISSUE THREAD

**Issue by Heesoomoon** [wellcometrust/wellcomecollection.org#4713]
## Purpose
To get more confidence in filter direction and validate following 
- Which filter model suits their research needs best?
- Usability: select/deselect, date entry
- Filter options: terminology, grouping, order
(Part of #4693)

## Methods
5x Internal (1:1 at their desk)
5x External (popup research in the viewing room)

## Prototype
Behind the toggles
- Refine filters prototype
- Explore filters prototype

## Tasks
- [x] Check with devs re build of thing to be tested and set deadline
- [x] Write script
- [ ] Review script with Product Manager
- [x] Pilot (optional)
- [x] Schedule 1:1 with internal users
- [x] Print research questions and ideas
- [ ] Book testing room (Viewing Room)
- [ ] Email LED about testing
- [ ] Drink voucher

**Comment by Heesoomoon** [comment]
User Research Summary
https://www.notion.so/wellcometrust/4713-User-Research-Search-Filter-fb2c0fc36afd4f4680912c0eb6760f32
