### ISSUE TITLE
User Research: Viewer

### ISSUE THREAD

**Issue by pollecuttn** [wellcometrust/wellcomecollection.org#4728]
### Aims/Purpose
- Evaluate how the current design support the process of reviewing a book
- Help the team to prioritise feature enhancements
https://github.com/wellcometrust/wellcomecollection.org/issues/4524

### Research Questions
- Can users find and navigate to relevant sections of the book? e.g. content pages to a chapter
- Can users read specific sentences on a given page? Any difficulties?
- Can users save the content they find?
- Are there any usability issues with the controls (view all, zoom, previous/next page, rotate)? Is it discoverable? is the function clear? Is it useful? Any missing controls?

### Tasks

- [x] Test run with Tacey to determine method of recruiting
- [x] Write script
- [x] Review script with Product Manager
- [x] Book testing room
- [x] Email team re observing and note taking

### Not in scope
Recommend an online survey with WL.org users to gather following insights
- How do they expect to save the content they found?
- What format do users expect to download?
- What download options do they require? whole book, chapter, specific pages,
