### ISSUE TITLE
Knock back zoom functionality when rendering digitised content

### ISSUE THREAD

**Issue by jennpb** [wellcometrust/wellcomecollection.org#4850]
# Problem to solve

Usability testing demonstrated that people still have trouble using deep zoom in OpenSeadragon on book-type things. This is because the action of zooming in to enlarge text then doesn't allow them to fall back on ingrained behaviour, like: 
- scrolling to move up/down the page
- moving to the next page 
- right-click to save image.

There is a tension here with the deepzoom world. 

If we can maximize the page viewing area, and downgrade the zoom functionality to secondary function, I hypothesise that users will be able to use this material much more naturally.

We know that:
- People are actively downloading/saving PDFs to read offline
- The majority of collections users are still primarily on larger screens (not doing their research on mobile)
- Zoom is great for detail on pictures, but not as useful as part of a reading experience.

# TODO
- [x] Instead of replacing the image in the viewer with an openseadragaon canvas, when a user chooses to zoom, the openseadragon canvas should open above the viewer and require the user to dismiss it in order to carry on navigating through the rest of the images within the viewer.
- [x] The rotate functionality that is currently provided by openseadragon, should still be available without using openseadragon.
- [x] Loading icons should inform the user visually and orally something is happening when rotate controls are used
- [x] Loading icons should inform the user visually and orally something is happening when openseadgradon is lauched.
- [x] Keyboard tabbing should be trapped inside the openseadragon viewer when it is open
- [x] Keyboard focus should be obvious to users
- [x] Test functionality across browsers/devices
- [ ] Viewer styling for relevant parts should match the new designs see: #4885  

# Other considerations 
- What will success look like? (engagement, more images viewed in work? usability testing)

**Comment by jennpb** [comment]
Part of #4848
