### ISSUE TITLE
SEO: Meta title, descriptions, and images

### ISSUE THREAD

**Issue by gestchild** [wellcometrust/wellcomecollection.org#534]
Not sure how important they are these days, but they couldn't hurt.  

"Google will sometimes use the meta description of a page in search results snippets, if we think it gives users a more accurate description than would be possible purely from the on-page content." - [Create good titles and snippets in Search Results](https://support.google.com/webmasters/answer/35624?hl=en)

This is also used on our opengraph / twitter metadata, thus sharing, so this is important.

For single items - we have all the info as needed.

We need:
- [ ] `/works` title, image, description
  Currently: Wellcome Collection search, nothing, nothing
- [ ] `/explore` title, image, description
  Currently: Explore, Exploration for the incurably curious, first image from promos
- [ ] `/articles` 
    Currently: Articles, nothing, first image from promos
- [ ] `/events` (page doesn't exist yet, but let's have it ready)
    Currently: Articles, nothing, first image from promos
- [ ] `/exhibitions` (page doesn't exist yet, but let's have it ready)
    Currently: Articles, nothing, first image from promos

**Comment by jennpb** [comment]
See #1099 for more detail

**Comment by jennpb** [comment]
Working document https://wellcomecloud-my.sharepoint.com/personal/j_phillips-bacher_wellcome_ac_uk/_layouts/15/guestaccess.aspx?guestaccesstoken=c2OHKslPVnakFsht%2bVRhwhky5Mt3bH7yQMEbLziOU2k%3d&docid=2_19e6848a3a11440e1a57477983a01ec34&rev=1

Need to hand over to content team
