### ISSUE TITLE
Migrate or deprecate Wordpress functionality

### ISSUE THREAD

**Issue by jennpb** [wellcometrust/wellcomecollection.org#814]
# Plan

There are no authors in Wordpress, they will have to be added after.

Images don't have credits in Wordpress - so they can't be brought across. __It wouldn't be too hard to have a tool that crawls our API looking for images without credits?__

Not all articles have a promo, featured image, and / or standfirst. This is documented in the spreadsheet of Wordpress articles: https://docs.google.com/spreadsheets/d/1MI_MBihke8bx77SqUXMAMKRCDajeAcSjWDPG1e7aVw8/edit

Jen S now has this spreadsheet and will be letting us know which to keep and which not to.

Once we have that list, we will do a few test imports to a test account to help not create clutter.

Once we're happy with this we can move to the live Prismic account with the articles we want, and stick them in a release. They can be released as and when.

When we're happy that we have a sufficient amount over, we can deprecate the Wellcome Collection ⇒ Wordpress integration.

Wordpress will still exist, but is only reachable from the admin interface.

# Things that have no known way to port over to Prismic

## Wordpress video
I have no idea how we might want to port these across - potentially download, upload to YT and re-embed?

[https://wellcomecollection.org/articles/pressure-drop-reunited-at-the-brit](https://wellcomecollection.org/articles/pressure-drop-reunited-at-the-brit)

[https://wellcomecollection.org/articles/pressure-drop-underneath-the-arches](https://wellcomecollection.org/articles/pressure-drop-underneath-the-arches)

[https://wellcomecollection.org/articles/rain-inside-a-room](https://wellcomecollection.org/articles/rain-inside-a-room)

[https://wellcomecollection.org/articles/the-making-of-death-a-picture-album](https://wellcomecollection.org/articles/the-making-of-death-a-picture-album)

[https://wellcomecollection.org/articles/breathing-for-speech](https://wellcomecollection.org/articles/breathing-for-speech)

[https://wellcomecollection.org/articles/bring-us-a-thing](https://wellcomecollection.org/articles/bring-us-a-thing)

[https://wellcomecollection.org/articles/voicings](https://wellcomecollection.org/articles/voicings)[https://wellcomecollection.org/articles/would-you-mind](https://wellcomecollection.org/articles/would-you-mind)

----
# past ticket

- [ ] Export all usage stats in case we need them https://wellcomecollection.wordpress.com/wp-admin/index.php?page=stats
- [ ] Decide how to bring WP email notification subscribers with us
- [ ] RSS? #528 
- [ ] Comments?
- [x] Migrate all Wordpress content to ~new content tool~ Prismic

**Comment by jennpb** [comment]
This is really clear to me - thank you @jamesgorrie . As for those questionable articles, let's wait till Jen goes through the list - we may be able to kill those, or rework them in context of other site content (particularly those relating to exhibitions or WC-published books)
