### ISSUE TITLE
Migrate content from Wordpress to Prismic.

### ISSUE THREAD

**Issue by jamesgorrie** [wellcometrust/wellcomecollection.org#887]
Export content from Wordpress into the format that prismic.io expects as an import.

https://prismic.io/docs/full-import-reference

**Comment by jamesgorrie** [comment]
Busy  in the process. Just some notes:
- [x] Author IDs need populating
- [ ] Nicola Cook and Lousja as authors doesn't work (Wordpress doesn't support multi-contributors)
-  [x] Some WP articles have added titles to galleries, let's apply those properly e.g. https://wellcomecollection.org/articles/outsiders-the-prostitute
- [ ] How do we attach digital stories... There are a few ideas, potentially creating them as separate  content type...

**Comment by jamesgorrie** [comment]
Close in favour of #814
