### ISSUE TITLE
Content production: Research Notes series

### ISSUE THREAD

**Issue by jennpb** [wellcometrust/wellcomecollection.org#918]
The Content team are intending to publish a series of articles under the banner of 'Research Notes'. These are roughly in line with Library blog content (or meant to replace Library blog content), with a strong focus on the research experience within the library itself. Library collections will play a large role - both visually and functionally - in this tranche of content.

We can use the existing Article template for this. An early days Explore page promo was designed - basically  just a 5 promo container with a differently coloured title. We need to confirm whether this is what we want. This also ties in well with:

- [ ] #902 - Creating a stronger identity for series
- [ ] #896 - Article: further reading
- [ ] #895 - Article: footnote
- [ ] #890 - Article: references
- [ ] #772 - Handling image titles, captions, credits across experience

![researchnotes](https://cloud.githubusercontent.com/assets/1446139/26302428/23eace9c-3edc-11e7-9eba-a01162fda416.png)

**Comment by Norvard** [comment]
I agree this needs to be looked at again as we have evolved what was there originally, and what we currently have serves content beyond what this was intended for.

@jennpb Who has the lead on this upcoming content? Maybe I can have a chat with them...

**Comment by jennpb** [comment]
It'll be Lalita who's leading. She's commissioning content for it now.

**Comment by Heesoomoon** [comment]
**14 June Meeting Note (Danny, Jenn, Heesoo and Tomi)**
Objectives: To clarify the goal of the Research Notes promo and decide on design direction.
- Research Notes highlights diverse types of research and process taken by experts
- Tagline: What’s it like digging into archives to unearth the past? Follow the research process with our guest writers. (from Wellcome Library Blog)
- Discussed 3 different approaches (Quotes, Question and Place+People). Decided to explore 'Question' direction.
- Potentially take over spot 2 in the Explore landing.

Next 
- Danny's team will provide short tagline
- Tomi will provide examples of single and multi articles for Research Notes promo block in the Explore page.

**Comment by Norvard** [comment]
Design solution after review with Dany, Jenn and Heesoo

Component block, initially designed for the Explore landing page, that promotes the article series Research Notes. Can also be used elsewhere one day.
The block showcases 3 articles, with a hierarchy of a single large article and two smaller ones. The articles shown, can be curated and chosen by the editorial team. As all new articles live within the rest of the page when published, this block could showcase older articles if desired. A curated set that represents the series and is relevant to reader.
Rather than utilise the article image, the entry point (and link) in this case is the large question text. How these questions are managed from CSS is TBD, they should also be part of article itself, possibly set within the stand-first element.
Author element should include title rather than standard Twitter handle.

**Design details:**
The background uses the Teal colour (hex 006272) at 10% opacity. 
The large article text also features Teal colour, at full opacity. 
The pattern at the end of the article utilises our Turquoise-graphics colour (hex 5cb8bf)

**Responsive:**
Large size: large article flush left. 2 small article top aligned with large article, flush right.
Medium: Large article flush left above. 2 small article top aligned below
Small: All articles stack, top article is large.

**Large size:**
----------------------------------------------------------------------------------
![screen shot 2017-06-15 at 13 34 15](https://user-images.githubusercontent.com/23660297/27181978-ac3fd92e-51d1-11e7-9dbd-8f1e14dc1289.png)


**Medium size:**
----------------------------------------------------------------------------------
![screen shot 2017-06-15 at 13 34 27](https://user-images.githubusercontent.com/23660297/27181989-b27fb868-51d1-11e7-991f-f284512c415e.png)


**Small size:**
----------------------------------------------------------------------------------
![wc_explore_mvp_mobile_20170614](https://user-images.githubusercontent.com/23660297/27181998-b68d3eb2-51d1-11e7-82ab-3d627e1ed90a.png)



Design files:
[Research Notes.zip](https://github.com/wellcometrust/wellcomecollection.org/files/1077638/Research.Notes.zip)
